// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rb/api/body_component_based_command.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "rb/api/command_header.pb.h"
#include "rb/api/arm_command.pb.h"
#include "rb/api/torso_command.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto;
namespace rb {
namespace api {
class BodyComponentBasedCommand;
struct BodyComponentBasedCommandDefaultTypeInternal;
extern BodyComponentBasedCommandDefaultTypeInternal _BodyComponentBasedCommand_default_instance_;
class BodyComponentBasedCommand_Feedback;
struct BodyComponentBasedCommand_FeedbackDefaultTypeInternal;
extern BodyComponentBasedCommand_FeedbackDefaultTypeInternal _BodyComponentBasedCommand_Feedback_default_instance_;
class BodyComponentBasedCommand_Request;
struct BodyComponentBasedCommand_RequestDefaultTypeInternal;
extern BodyComponentBasedCommand_RequestDefaultTypeInternal _BodyComponentBasedCommand_Request_default_instance_;
}  // namespace api
}  // namespace rb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace rb {
namespace api {

// ===================================================================


// -------------------------------------------------------------------

class BodyComponentBasedCommand final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:rb.api.BodyComponentBasedCommand) */ {
 public:
  inline BodyComponentBasedCommand() : BodyComponentBasedCommand(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BodyComponentBasedCommand(
      ::google::protobuf::internal::ConstantInitialized);

  inline BodyComponentBasedCommand(const BodyComponentBasedCommand& from) : BodyComponentBasedCommand(nullptr, from) {}
  inline BodyComponentBasedCommand(BodyComponentBasedCommand&& from) noexcept
      : BodyComponentBasedCommand(nullptr, std::move(from)) {}
  inline BodyComponentBasedCommand& operator=(const BodyComponentBasedCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline BodyComponentBasedCommand& operator=(BodyComponentBasedCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BodyComponentBasedCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const BodyComponentBasedCommand* internal_default_instance() {
    return reinterpret_cast<const BodyComponentBasedCommand*>(
        &_BodyComponentBasedCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(BodyComponentBasedCommand& a, BodyComponentBasedCommand& b) { a.Swap(&b); }
  inline void Swap(BodyComponentBasedCommand* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BodyComponentBasedCommand* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BodyComponentBasedCommand* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<BodyComponentBasedCommand>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const BodyComponentBasedCommand& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const BodyComponentBasedCommand& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "rb.api.BodyComponentBasedCommand"; }

 protected:
  explicit BodyComponentBasedCommand(::google::protobuf::Arena* arena);
  BodyComponentBasedCommand(::google::protobuf::Arena* arena, const BodyComponentBasedCommand& from);
  BodyComponentBasedCommand(::google::protobuf::Arena* arena, BodyComponentBasedCommand&& from) noexcept
      : BodyComponentBasedCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Request = BodyComponentBasedCommand_Request;
  using Feedback = BodyComponentBasedCommand_Feedback;

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:rb.api.BodyComponentBasedCommand)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_BodyComponentBasedCommand_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BodyComponentBasedCommand& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto;
};
// -------------------------------------------------------------------

class BodyComponentBasedCommand_Feedback final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rb.api.BodyComponentBasedCommand.Feedback) */ {
 public:
  inline BodyComponentBasedCommand_Feedback() : BodyComponentBasedCommand_Feedback(nullptr) {}
  ~BodyComponentBasedCommand_Feedback() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BodyComponentBasedCommand_Feedback(
      ::google::protobuf::internal::ConstantInitialized);

  inline BodyComponentBasedCommand_Feedback(const BodyComponentBasedCommand_Feedback& from) : BodyComponentBasedCommand_Feedback(nullptr, from) {}
  inline BodyComponentBasedCommand_Feedback(BodyComponentBasedCommand_Feedback&& from) noexcept
      : BodyComponentBasedCommand_Feedback(nullptr, std::move(from)) {}
  inline BodyComponentBasedCommand_Feedback& operator=(const BodyComponentBasedCommand_Feedback& from) {
    CopyFrom(from);
    return *this;
  }
  inline BodyComponentBasedCommand_Feedback& operator=(BodyComponentBasedCommand_Feedback&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BodyComponentBasedCommand_Feedback& default_instance() {
    return *internal_default_instance();
  }
  static inline const BodyComponentBasedCommand_Feedback* internal_default_instance() {
    return reinterpret_cast<const BodyComponentBasedCommand_Feedback*>(
        &_BodyComponentBasedCommand_Feedback_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BodyComponentBasedCommand_Feedback& a, BodyComponentBasedCommand_Feedback& b) { a.Swap(&b); }
  inline void Swap(BodyComponentBasedCommand_Feedback* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BodyComponentBasedCommand_Feedback* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BodyComponentBasedCommand_Feedback* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<BodyComponentBasedCommand_Feedback>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BodyComponentBasedCommand_Feedback& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BodyComponentBasedCommand_Feedback& from) { BodyComponentBasedCommand_Feedback::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(BodyComponentBasedCommand_Feedback* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "rb.api.BodyComponentBasedCommand.Feedback"; }

 protected:
  explicit BodyComponentBasedCommand_Feedback(::google::protobuf::Arena* arena);
  BodyComponentBasedCommand_Feedback(::google::protobuf::Arena* arena, const BodyComponentBasedCommand_Feedback& from);
  BodyComponentBasedCommand_Feedback(::google::protobuf::Arena* arena, BodyComponentBasedCommand_Feedback&& from) noexcept
      : BodyComponentBasedCommand_Feedback(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandHeaderFeedbackFieldNumber = 1,
    kRightArmCommandFeedbackFieldNumber = 2,
    kLeftArmCommandFeedbackFieldNumber = 3,
    kTorsoCommandFeedbackFieldNumber = 4,
  };
  // .rb.api.CommandHeader.Feedback command_header_feedback = 1;
  bool has_command_header_feedback() const;
  void clear_command_header_feedback() ;
  const ::rb::api::CommandHeader_Feedback& command_header_feedback() const;
  PROTOBUF_NODISCARD ::rb::api::CommandHeader_Feedback* release_command_header_feedback();
  ::rb::api::CommandHeader_Feedback* mutable_command_header_feedback();
  void set_allocated_command_header_feedback(::rb::api::CommandHeader_Feedback* value);
  void unsafe_arena_set_allocated_command_header_feedback(::rb::api::CommandHeader_Feedback* value);
  ::rb::api::CommandHeader_Feedback* unsafe_arena_release_command_header_feedback();

  private:
  const ::rb::api::CommandHeader_Feedback& _internal_command_header_feedback() const;
  ::rb::api::CommandHeader_Feedback* _internal_mutable_command_header_feedback();

  public:
  // .rb.api.ArmCommand.Feedback right_arm_command_feedback = 2;
  bool has_right_arm_command_feedback() const;
  void clear_right_arm_command_feedback() ;
  const ::rb::api::ArmCommand_Feedback& right_arm_command_feedback() const;
  PROTOBUF_NODISCARD ::rb::api::ArmCommand_Feedback* release_right_arm_command_feedback();
  ::rb::api::ArmCommand_Feedback* mutable_right_arm_command_feedback();
  void set_allocated_right_arm_command_feedback(::rb::api::ArmCommand_Feedback* value);
  void unsafe_arena_set_allocated_right_arm_command_feedback(::rb::api::ArmCommand_Feedback* value);
  ::rb::api::ArmCommand_Feedback* unsafe_arena_release_right_arm_command_feedback();

  private:
  const ::rb::api::ArmCommand_Feedback& _internal_right_arm_command_feedback() const;
  ::rb::api::ArmCommand_Feedback* _internal_mutable_right_arm_command_feedback();

  public:
  // .rb.api.ArmCommand.Feedback left_arm_command_feedback = 3;
  bool has_left_arm_command_feedback() const;
  void clear_left_arm_command_feedback() ;
  const ::rb::api::ArmCommand_Feedback& left_arm_command_feedback() const;
  PROTOBUF_NODISCARD ::rb::api::ArmCommand_Feedback* release_left_arm_command_feedback();
  ::rb::api::ArmCommand_Feedback* mutable_left_arm_command_feedback();
  void set_allocated_left_arm_command_feedback(::rb::api::ArmCommand_Feedback* value);
  void unsafe_arena_set_allocated_left_arm_command_feedback(::rb::api::ArmCommand_Feedback* value);
  ::rb::api::ArmCommand_Feedback* unsafe_arena_release_left_arm_command_feedback();

  private:
  const ::rb::api::ArmCommand_Feedback& _internal_left_arm_command_feedback() const;
  ::rb::api::ArmCommand_Feedback* _internal_mutable_left_arm_command_feedback();

  public:
  // .rb.api.TorsoCommand.Feedback torso_command_feedback = 4;
  bool has_torso_command_feedback() const;
  void clear_torso_command_feedback() ;
  const ::rb::api::TorsoCommand_Feedback& torso_command_feedback() const;
  PROTOBUF_NODISCARD ::rb::api::TorsoCommand_Feedback* release_torso_command_feedback();
  ::rb::api::TorsoCommand_Feedback* mutable_torso_command_feedback();
  void set_allocated_torso_command_feedback(::rb::api::TorsoCommand_Feedback* value);
  void unsafe_arena_set_allocated_torso_command_feedback(::rb::api::TorsoCommand_Feedback* value);
  ::rb::api::TorsoCommand_Feedback* unsafe_arena_release_torso_command_feedback();

  private:
  const ::rb::api::TorsoCommand_Feedback& _internal_torso_command_feedback() const;
  ::rb::api::TorsoCommand_Feedback* _internal_mutable_torso_command_feedback();

  public:
  // @@protoc_insertion_point(class_scope:rb.api.BodyComponentBasedCommand.Feedback)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 4,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_BodyComponentBasedCommand_Feedback_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BodyComponentBasedCommand_Feedback& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::rb::api::CommandHeader_Feedback* command_header_feedback_;
    ::rb::api::ArmCommand_Feedback* right_arm_command_feedback_;
    ::rb::api::ArmCommand_Feedback* left_arm_command_feedback_;
    ::rb::api::TorsoCommand_Feedback* torso_command_feedback_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto;
};
// -------------------------------------------------------------------

class BodyComponentBasedCommand_Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rb.api.BodyComponentBasedCommand.Request) */ {
 public:
  inline BodyComponentBasedCommand_Request() : BodyComponentBasedCommand_Request(nullptr) {}
  ~BodyComponentBasedCommand_Request() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BodyComponentBasedCommand_Request(
      ::google::protobuf::internal::ConstantInitialized);

  inline BodyComponentBasedCommand_Request(const BodyComponentBasedCommand_Request& from) : BodyComponentBasedCommand_Request(nullptr, from) {}
  inline BodyComponentBasedCommand_Request(BodyComponentBasedCommand_Request&& from) noexcept
      : BodyComponentBasedCommand_Request(nullptr, std::move(from)) {}
  inline BodyComponentBasedCommand_Request& operator=(const BodyComponentBasedCommand_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline BodyComponentBasedCommand_Request& operator=(BodyComponentBasedCommand_Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BodyComponentBasedCommand_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const BodyComponentBasedCommand_Request* internal_default_instance() {
    return reinterpret_cast<const BodyComponentBasedCommand_Request*>(
        &_BodyComponentBasedCommand_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BodyComponentBasedCommand_Request& a, BodyComponentBasedCommand_Request& b) { a.Swap(&b); }
  inline void Swap(BodyComponentBasedCommand_Request* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BodyComponentBasedCommand_Request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BodyComponentBasedCommand_Request* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<BodyComponentBasedCommand_Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BodyComponentBasedCommand_Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BodyComponentBasedCommand_Request& from) { BodyComponentBasedCommand_Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(BodyComponentBasedCommand_Request* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "rb.api.BodyComponentBasedCommand.Request"; }

 protected:
  explicit BodyComponentBasedCommand_Request(::google::protobuf::Arena* arena);
  BodyComponentBasedCommand_Request(::google::protobuf::Arena* arena, const BodyComponentBasedCommand_Request& from);
  BodyComponentBasedCommand_Request(::google::protobuf::Arena* arena, BodyComponentBasedCommand_Request&& from) noexcept
      : BodyComponentBasedCommand_Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandHeaderFieldNumber = 1,
    kRightArmCommandFieldNumber = 2,
    kLeftArmCommandFieldNumber = 3,
    kTorsoCommandFieldNumber = 4,
  };
  // .rb.api.CommandHeader.Request command_header = 1;
  bool has_command_header() const;
  void clear_command_header() ;
  const ::rb::api::CommandHeader_Request& command_header() const;
  PROTOBUF_NODISCARD ::rb::api::CommandHeader_Request* release_command_header();
  ::rb::api::CommandHeader_Request* mutable_command_header();
  void set_allocated_command_header(::rb::api::CommandHeader_Request* value);
  void unsafe_arena_set_allocated_command_header(::rb::api::CommandHeader_Request* value);
  ::rb::api::CommandHeader_Request* unsafe_arena_release_command_header();

  private:
  const ::rb::api::CommandHeader_Request& _internal_command_header() const;
  ::rb::api::CommandHeader_Request* _internal_mutable_command_header();

  public:
  // .rb.api.ArmCommand.Request right_arm_command = 2;
  bool has_right_arm_command() const;
  void clear_right_arm_command() ;
  const ::rb::api::ArmCommand_Request& right_arm_command() const;
  PROTOBUF_NODISCARD ::rb::api::ArmCommand_Request* release_right_arm_command();
  ::rb::api::ArmCommand_Request* mutable_right_arm_command();
  void set_allocated_right_arm_command(::rb::api::ArmCommand_Request* value);
  void unsafe_arena_set_allocated_right_arm_command(::rb::api::ArmCommand_Request* value);
  ::rb::api::ArmCommand_Request* unsafe_arena_release_right_arm_command();

  private:
  const ::rb::api::ArmCommand_Request& _internal_right_arm_command() const;
  ::rb::api::ArmCommand_Request* _internal_mutable_right_arm_command();

  public:
  // .rb.api.ArmCommand.Request left_arm_command = 3;
  bool has_left_arm_command() const;
  void clear_left_arm_command() ;
  const ::rb::api::ArmCommand_Request& left_arm_command() const;
  PROTOBUF_NODISCARD ::rb::api::ArmCommand_Request* release_left_arm_command();
  ::rb::api::ArmCommand_Request* mutable_left_arm_command();
  void set_allocated_left_arm_command(::rb::api::ArmCommand_Request* value);
  void unsafe_arena_set_allocated_left_arm_command(::rb::api::ArmCommand_Request* value);
  ::rb::api::ArmCommand_Request* unsafe_arena_release_left_arm_command();

  private:
  const ::rb::api::ArmCommand_Request& _internal_left_arm_command() const;
  ::rb::api::ArmCommand_Request* _internal_mutable_left_arm_command();

  public:
  // .rb.api.TorsoCommand.Request torso_command = 4;
  bool has_torso_command() const;
  void clear_torso_command() ;
  const ::rb::api::TorsoCommand_Request& torso_command() const;
  PROTOBUF_NODISCARD ::rb::api::TorsoCommand_Request* release_torso_command();
  ::rb::api::TorsoCommand_Request* mutable_torso_command();
  void set_allocated_torso_command(::rb::api::TorsoCommand_Request* value);
  void unsafe_arena_set_allocated_torso_command(::rb::api::TorsoCommand_Request* value);
  ::rb::api::TorsoCommand_Request* unsafe_arena_release_torso_command();

  private:
  const ::rb::api::TorsoCommand_Request& _internal_torso_command() const;
  ::rb::api::TorsoCommand_Request* _internal_mutable_torso_command();

  public:
  // @@protoc_insertion_point(class_scope:rb.api.BodyComponentBasedCommand.Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 4,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_BodyComponentBasedCommand_Request_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BodyComponentBasedCommand_Request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::rb::api::CommandHeader_Request* command_header_;
    ::rb::api::ArmCommand_Request* right_arm_command_;
    ::rb::api::ArmCommand_Request* left_arm_command_;
    ::rb::api::TorsoCommand_Request* torso_command_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BodyComponentBasedCommand_Request

// .rb.api.CommandHeader.Request command_header = 1;
inline bool BodyComponentBasedCommand_Request::has_command_header() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.command_header_ != nullptr);
  return value;
}
inline const ::rb::api::CommandHeader_Request& BodyComponentBasedCommand_Request::_internal_command_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::rb::api::CommandHeader_Request* p = _impl_.command_header_;
  return p != nullptr ? *p : reinterpret_cast<const ::rb::api::CommandHeader_Request&>(::rb::api::_CommandHeader_Request_default_instance_);
}
inline const ::rb::api::CommandHeader_Request& BodyComponentBasedCommand_Request::command_header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rb.api.BodyComponentBasedCommand.Request.command_header)
  return _internal_command_header();
}
inline void BodyComponentBasedCommand_Request::unsafe_arena_set_allocated_command_header(::rb::api::CommandHeader_Request* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.command_header_);
  }
  _impl_.command_header_ = reinterpret_cast<::rb::api::CommandHeader_Request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rb.api.BodyComponentBasedCommand.Request.command_header)
}
inline ::rb::api::CommandHeader_Request* BodyComponentBasedCommand_Request::release_command_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::rb::api::CommandHeader_Request* released = _impl_.command_header_;
  _impl_.command_header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::rb::api::CommandHeader_Request* BodyComponentBasedCommand_Request::unsafe_arena_release_command_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rb.api.BodyComponentBasedCommand.Request.command_header)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::rb::api::CommandHeader_Request* temp = _impl_.command_header_;
  _impl_.command_header_ = nullptr;
  return temp;
}
inline ::rb::api::CommandHeader_Request* BodyComponentBasedCommand_Request::_internal_mutable_command_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.command_header_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::rb::api::CommandHeader_Request>(GetArena());
    _impl_.command_header_ = reinterpret_cast<::rb::api::CommandHeader_Request*>(p);
  }
  return _impl_.command_header_;
}
inline ::rb::api::CommandHeader_Request* BodyComponentBasedCommand_Request::mutable_command_header() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::rb::api::CommandHeader_Request* _msg = _internal_mutable_command_header();
  // @@protoc_insertion_point(field_mutable:rb.api.BodyComponentBasedCommand.Request.command_header)
  return _msg;
}
inline void BodyComponentBasedCommand_Request::set_allocated_command_header(::rb::api::CommandHeader_Request* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.command_header_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.command_header_ = reinterpret_cast<::rb::api::CommandHeader_Request*>(value);
  // @@protoc_insertion_point(field_set_allocated:rb.api.BodyComponentBasedCommand.Request.command_header)
}

// .rb.api.ArmCommand.Request right_arm_command = 2;
inline bool BodyComponentBasedCommand_Request::has_right_arm_command() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.right_arm_command_ != nullptr);
  return value;
}
inline const ::rb::api::ArmCommand_Request& BodyComponentBasedCommand_Request::_internal_right_arm_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::rb::api::ArmCommand_Request* p = _impl_.right_arm_command_;
  return p != nullptr ? *p : reinterpret_cast<const ::rb::api::ArmCommand_Request&>(::rb::api::_ArmCommand_Request_default_instance_);
}
inline const ::rb::api::ArmCommand_Request& BodyComponentBasedCommand_Request::right_arm_command() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rb.api.BodyComponentBasedCommand.Request.right_arm_command)
  return _internal_right_arm_command();
}
inline void BodyComponentBasedCommand_Request::unsafe_arena_set_allocated_right_arm_command(::rb::api::ArmCommand_Request* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.right_arm_command_);
  }
  _impl_.right_arm_command_ = reinterpret_cast<::rb::api::ArmCommand_Request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rb.api.BodyComponentBasedCommand.Request.right_arm_command)
}
inline ::rb::api::ArmCommand_Request* BodyComponentBasedCommand_Request::release_right_arm_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::rb::api::ArmCommand_Request* released = _impl_.right_arm_command_;
  _impl_.right_arm_command_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::rb::api::ArmCommand_Request* BodyComponentBasedCommand_Request::unsafe_arena_release_right_arm_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rb.api.BodyComponentBasedCommand.Request.right_arm_command)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::rb::api::ArmCommand_Request* temp = _impl_.right_arm_command_;
  _impl_.right_arm_command_ = nullptr;
  return temp;
}
inline ::rb::api::ArmCommand_Request* BodyComponentBasedCommand_Request::_internal_mutable_right_arm_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.right_arm_command_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::rb::api::ArmCommand_Request>(GetArena());
    _impl_.right_arm_command_ = reinterpret_cast<::rb::api::ArmCommand_Request*>(p);
  }
  return _impl_.right_arm_command_;
}
inline ::rb::api::ArmCommand_Request* BodyComponentBasedCommand_Request::mutable_right_arm_command() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::rb::api::ArmCommand_Request* _msg = _internal_mutable_right_arm_command();
  // @@protoc_insertion_point(field_mutable:rb.api.BodyComponentBasedCommand.Request.right_arm_command)
  return _msg;
}
inline void BodyComponentBasedCommand_Request::set_allocated_right_arm_command(::rb::api::ArmCommand_Request* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.right_arm_command_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.right_arm_command_ = reinterpret_cast<::rb::api::ArmCommand_Request*>(value);
  // @@protoc_insertion_point(field_set_allocated:rb.api.BodyComponentBasedCommand.Request.right_arm_command)
}

// .rb.api.ArmCommand.Request left_arm_command = 3;
inline bool BodyComponentBasedCommand_Request::has_left_arm_command() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.left_arm_command_ != nullptr);
  return value;
}
inline const ::rb::api::ArmCommand_Request& BodyComponentBasedCommand_Request::_internal_left_arm_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::rb::api::ArmCommand_Request* p = _impl_.left_arm_command_;
  return p != nullptr ? *p : reinterpret_cast<const ::rb::api::ArmCommand_Request&>(::rb::api::_ArmCommand_Request_default_instance_);
}
inline const ::rb::api::ArmCommand_Request& BodyComponentBasedCommand_Request::left_arm_command() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rb.api.BodyComponentBasedCommand.Request.left_arm_command)
  return _internal_left_arm_command();
}
inline void BodyComponentBasedCommand_Request::unsafe_arena_set_allocated_left_arm_command(::rb::api::ArmCommand_Request* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.left_arm_command_);
  }
  _impl_.left_arm_command_ = reinterpret_cast<::rb::api::ArmCommand_Request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rb.api.BodyComponentBasedCommand.Request.left_arm_command)
}
inline ::rb::api::ArmCommand_Request* BodyComponentBasedCommand_Request::release_left_arm_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::rb::api::ArmCommand_Request* released = _impl_.left_arm_command_;
  _impl_.left_arm_command_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::rb::api::ArmCommand_Request* BodyComponentBasedCommand_Request::unsafe_arena_release_left_arm_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rb.api.BodyComponentBasedCommand.Request.left_arm_command)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::rb::api::ArmCommand_Request* temp = _impl_.left_arm_command_;
  _impl_.left_arm_command_ = nullptr;
  return temp;
}
inline ::rb::api::ArmCommand_Request* BodyComponentBasedCommand_Request::_internal_mutable_left_arm_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.left_arm_command_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::rb::api::ArmCommand_Request>(GetArena());
    _impl_.left_arm_command_ = reinterpret_cast<::rb::api::ArmCommand_Request*>(p);
  }
  return _impl_.left_arm_command_;
}
inline ::rb::api::ArmCommand_Request* BodyComponentBasedCommand_Request::mutable_left_arm_command() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::rb::api::ArmCommand_Request* _msg = _internal_mutable_left_arm_command();
  // @@protoc_insertion_point(field_mutable:rb.api.BodyComponentBasedCommand.Request.left_arm_command)
  return _msg;
}
inline void BodyComponentBasedCommand_Request::set_allocated_left_arm_command(::rb::api::ArmCommand_Request* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.left_arm_command_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.left_arm_command_ = reinterpret_cast<::rb::api::ArmCommand_Request*>(value);
  // @@protoc_insertion_point(field_set_allocated:rb.api.BodyComponentBasedCommand.Request.left_arm_command)
}

// .rb.api.TorsoCommand.Request torso_command = 4;
inline bool BodyComponentBasedCommand_Request::has_torso_command() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.torso_command_ != nullptr);
  return value;
}
inline const ::rb::api::TorsoCommand_Request& BodyComponentBasedCommand_Request::_internal_torso_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::rb::api::TorsoCommand_Request* p = _impl_.torso_command_;
  return p != nullptr ? *p : reinterpret_cast<const ::rb::api::TorsoCommand_Request&>(::rb::api::_TorsoCommand_Request_default_instance_);
}
inline const ::rb::api::TorsoCommand_Request& BodyComponentBasedCommand_Request::torso_command() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rb.api.BodyComponentBasedCommand.Request.torso_command)
  return _internal_torso_command();
}
inline void BodyComponentBasedCommand_Request::unsafe_arena_set_allocated_torso_command(::rb::api::TorsoCommand_Request* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.torso_command_);
  }
  _impl_.torso_command_ = reinterpret_cast<::rb::api::TorsoCommand_Request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rb.api.BodyComponentBasedCommand.Request.torso_command)
}
inline ::rb::api::TorsoCommand_Request* BodyComponentBasedCommand_Request::release_torso_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::rb::api::TorsoCommand_Request* released = _impl_.torso_command_;
  _impl_.torso_command_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::rb::api::TorsoCommand_Request* BodyComponentBasedCommand_Request::unsafe_arena_release_torso_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rb.api.BodyComponentBasedCommand.Request.torso_command)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::rb::api::TorsoCommand_Request* temp = _impl_.torso_command_;
  _impl_.torso_command_ = nullptr;
  return temp;
}
inline ::rb::api::TorsoCommand_Request* BodyComponentBasedCommand_Request::_internal_mutable_torso_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.torso_command_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::rb::api::TorsoCommand_Request>(GetArena());
    _impl_.torso_command_ = reinterpret_cast<::rb::api::TorsoCommand_Request*>(p);
  }
  return _impl_.torso_command_;
}
inline ::rb::api::TorsoCommand_Request* BodyComponentBasedCommand_Request::mutable_torso_command() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::rb::api::TorsoCommand_Request* _msg = _internal_mutable_torso_command();
  // @@protoc_insertion_point(field_mutable:rb.api.BodyComponentBasedCommand.Request.torso_command)
  return _msg;
}
inline void BodyComponentBasedCommand_Request::set_allocated_torso_command(::rb::api::TorsoCommand_Request* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.torso_command_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.torso_command_ = reinterpret_cast<::rb::api::TorsoCommand_Request*>(value);
  // @@protoc_insertion_point(field_set_allocated:rb.api.BodyComponentBasedCommand.Request.torso_command)
}

// -------------------------------------------------------------------

// BodyComponentBasedCommand_Feedback

// .rb.api.CommandHeader.Feedback command_header_feedback = 1;
inline bool BodyComponentBasedCommand_Feedback::has_command_header_feedback() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.command_header_feedback_ != nullptr);
  return value;
}
inline const ::rb::api::CommandHeader_Feedback& BodyComponentBasedCommand_Feedback::_internal_command_header_feedback() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::rb::api::CommandHeader_Feedback* p = _impl_.command_header_feedback_;
  return p != nullptr ? *p : reinterpret_cast<const ::rb::api::CommandHeader_Feedback&>(::rb::api::_CommandHeader_Feedback_default_instance_);
}
inline const ::rb::api::CommandHeader_Feedback& BodyComponentBasedCommand_Feedback::command_header_feedback() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rb.api.BodyComponentBasedCommand.Feedback.command_header_feedback)
  return _internal_command_header_feedback();
}
inline void BodyComponentBasedCommand_Feedback::unsafe_arena_set_allocated_command_header_feedback(::rb::api::CommandHeader_Feedback* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.command_header_feedback_);
  }
  _impl_.command_header_feedback_ = reinterpret_cast<::rb::api::CommandHeader_Feedback*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rb.api.BodyComponentBasedCommand.Feedback.command_header_feedback)
}
inline ::rb::api::CommandHeader_Feedback* BodyComponentBasedCommand_Feedback::release_command_header_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::rb::api::CommandHeader_Feedback* released = _impl_.command_header_feedback_;
  _impl_.command_header_feedback_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::rb::api::CommandHeader_Feedback* BodyComponentBasedCommand_Feedback::unsafe_arena_release_command_header_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rb.api.BodyComponentBasedCommand.Feedback.command_header_feedback)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::rb::api::CommandHeader_Feedback* temp = _impl_.command_header_feedback_;
  _impl_.command_header_feedback_ = nullptr;
  return temp;
}
inline ::rb::api::CommandHeader_Feedback* BodyComponentBasedCommand_Feedback::_internal_mutable_command_header_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.command_header_feedback_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::rb::api::CommandHeader_Feedback>(GetArena());
    _impl_.command_header_feedback_ = reinterpret_cast<::rb::api::CommandHeader_Feedback*>(p);
  }
  return _impl_.command_header_feedback_;
}
inline ::rb::api::CommandHeader_Feedback* BodyComponentBasedCommand_Feedback::mutable_command_header_feedback() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::rb::api::CommandHeader_Feedback* _msg = _internal_mutable_command_header_feedback();
  // @@protoc_insertion_point(field_mutable:rb.api.BodyComponentBasedCommand.Feedback.command_header_feedback)
  return _msg;
}
inline void BodyComponentBasedCommand_Feedback::set_allocated_command_header_feedback(::rb::api::CommandHeader_Feedback* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.command_header_feedback_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.command_header_feedback_ = reinterpret_cast<::rb::api::CommandHeader_Feedback*>(value);
  // @@protoc_insertion_point(field_set_allocated:rb.api.BodyComponentBasedCommand.Feedback.command_header_feedback)
}

// .rb.api.ArmCommand.Feedback right_arm_command_feedback = 2;
inline bool BodyComponentBasedCommand_Feedback::has_right_arm_command_feedback() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.right_arm_command_feedback_ != nullptr);
  return value;
}
inline const ::rb::api::ArmCommand_Feedback& BodyComponentBasedCommand_Feedback::_internal_right_arm_command_feedback() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::rb::api::ArmCommand_Feedback* p = _impl_.right_arm_command_feedback_;
  return p != nullptr ? *p : reinterpret_cast<const ::rb::api::ArmCommand_Feedback&>(::rb::api::_ArmCommand_Feedback_default_instance_);
}
inline const ::rb::api::ArmCommand_Feedback& BodyComponentBasedCommand_Feedback::right_arm_command_feedback() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rb.api.BodyComponentBasedCommand.Feedback.right_arm_command_feedback)
  return _internal_right_arm_command_feedback();
}
inline void BodyComponentBasedCommand_Feedback::unsafe_arena_set_allocated_right_arm_command_feedback(::rb::api::ArmCommand_Feedback* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.right_arm_command_feedback_);
  }
  _impl_.right_arm_command_feedback_ = reinterpret_cast<::rb::api::ArmCommand_Feedback*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rb.api.BodyComponentBasedCommand.Feedback.right_arm_command_feedback)
}
inline ::rb::api::ArmCommand_Feedback* BodyComponentBasedCommand_Feedback::release_right_arm_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::rb::api::ArmCommand_Feedback* released = _impl_.right_arm_command_feedback_;
  _impl_.right_arm_command_feedback_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::rb::api::ArmCommand_Feedback* BodyComponentBasedCommand_Feedback::unsafe_arena_release_right_arm_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rb.api.BodyComponentBasedCommand.Feedback.right_arm_command_feedback)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::rb::api::ArmCommand_Feedback* temp = _impl_.right_arm_command_feedback_;
  _impl_.right_arm_command_feedback_ = nullptr;
  return temp;
}
inline ::rb::api::ArmCommand_Feedback* BodyComponentBasedCommand_Feedback::_internal_mutable_right_arm_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.right_arm_command_feedback_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::rb::api::ArmCommand_Feedback>(GetArena());
    _impl_.right_arm_command_feedback_ = reinterpret_cast<::rb::api::ArmCommand_Feedback*>(p);
  }
  return _impl_.right_arm_command_feedback_;
}
inline ::rb::api::ArmCommand_Feedback* BodyComponentBasedCommand_Feedback::mutable_right_arm_command_feedback() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::rb::api::ArmCommand_Feedback* _msg = _internal_mutable_right_arm_command_feedback();
  // @@protoc_insertion_point(field_mutable:rb.api.BodyComponentBasedCommand.Feedback.right_arm_command_feedback)
  return _msg;
}
inline void BodyComponentBasedCommand_Feedback::set_allocated_right_arm_command_feedback(::rb::api::ArmCommand_Feedback* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.right_arm_command_feedback_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.right_arm_command_feedback_ = reinterpret_cast<::rb::api::ArmCommand_Feedback*>(value);
  // @@protoc_insertion_point(field_set_allocated:rb.api.BodyComponentBasedCommand.Feedback.right_arm_command_feedback)
}

// .rb.api.ArmCommand.Feedback left_arm_command_feedback = 3;
inline bool BodyComponentBasedCommand_Feedback::has_left_arm_command_feedback() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.left_arm_command_feedback_ != nullptr);
  return value;
}
inline const ::rb::api::ArmCommand_Feedback& BodyComponentBasedCommand_Feedback::_internal_left_arm_command_feedback() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::rb::api::ArmCommand_Feedback* p = _impl_.left_arm_command_feedback_;
  return p != nullptr ? *p : reinterpret_cast<const ::rb::api::ArmCommand_Feedback&>(::rb::api::_ArmCommand_Feedback_default_instance_);
}
inline const ::rb::api::ArmCommand_Feedback& BodyComponentBasedCommand_Feedback::left_arm_command_feedback() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rb.api.BodyComponentBasedCommand.Feedback.left_arm_command_feedback)
  return _internal_left_arm_command_feedback();
}
inline void BodyComponentBasedCommand_Feedback::unsafe_arena_set_allocated_left_arm_command_feedback(::rb::api::ArmCommand_Feedback* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.left_arm_command_feedback_);
  }
  _impl_.left_arm_command_feedback_ = reinterpret_cast<::rb::api::ArmCommand_Feedback*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rb.api.BodyComponentBasedCommand.Feedback.left_arm_command_feedback)
}
inline ::rb::api::ArmCommand_Feedback* BodyComponentBasedCommand_Feedback::release_left_arm_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::rb::api::ArmCommand_Feedback* released = _impl_.left_arm_command_feedback_;
  _impl_.left_arm_command_feedback_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::rb::api::ArmCommand_Feedback* BodyComponentBasedCommand_Feedback::unsafe_arena_release_left_arm_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rb.api.BodyComponentBasedCommand.Feedback.left_arm_command_feedback)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::rb::api::ArmCommand_Feedback* temp = _impl_.left_arm_command_feedback_;
  _impl_.left_arm_command_feedback_ = nullptr;
  return temp;
}
inline ::rb::api::ArmCommand_Feedback* BodyComponentBasedCommand_Feedback::_internal_mutable_left_arm_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.left_arm_command_feedback_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::rb::api::ArmCommand_Feedback>(GetArena());
    _impl_.left_arm_command_feedback_ = reinterpret_cast<::rb::api::ArmCommand_Feedback*>(p);
  }
  return _impl_.left_arm_command_feedback_;
}
inline ::rb::api::ArmCommand_Feedback* BodyComponentBasedCommand_Feedback::mutable_left_arm_command_feedback() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::rb::api::ArmCommand_Feedback* _msg = _internal_mutable_left_arm_command_feedback();
  // @@protoc_insertion_point(field_mutable:rb.api.BodyComponentBasedCommand.Feedback.left_arm_command_feedback)
  return _msg;
}
inline void BodyComponentBasedCommand_Feedback::set_allocated_left_arm_command_feedback(::rb::api::ArmCommand_Feedback* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.left_arm_command_feedback_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.left_arm_command_feedback_ = reinterpret_cast<::rb::api::ArmCommand_Feedback*>(value);
  // @@protoc_insertion_point(field_set_allocated:rb.api.BodyComponentBasedCommand.Feedback.left_arm_command_feedback)
}

// .rb.api.TorsoCommand.Feedback torso_command_feedback = 4;
inline bool BodyComponentBasedCommand_Feedback::has_torso_command_feedback() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.torso_command_feedback_ != nullptr);
  return value;
}
inline const ::rb::api::TorsoCommand_Feedback& BodyComponentBasedCommand_Feedback::_internal_torso_command_feedback() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::rb::api::TorsoCommand_Feedback* p = _impl_.torso_command_feedback_;
  return p != nullptr ? *p : reinterpret_cast<const ::rb::api::TorsoCommand_Feedback&>(::rb::api::_TorsoCommand_Feedback_default_instance_);
}
inline const ::rb::api::TorsoCommand_Feedback& BodyComponentBasedCommand_Feedback::torso_command_feedback() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rb.api.BodyComponentBasedCommand.Feedback.torso_command_feedback)
  return _internal_torso_command_feedback();
}
inline void BodyComponentBasedCommand_Feedback::unsafe_arena_set_allocated_torso_command_feedback(::rb::api::TorsoCommand_Feedback* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.torso_command_feedback_);
  }
  _impl_.torso_command_feedback_ = reinterpret_cast<::rb::api::TorsoCommand_Feedback*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rb.api.BodyComponentBasedCommand.Feedback.torso_command_feedback)
}
inline ::rb::api::TorsoCommand_Feedback* BodyComponentBasedCommand_Feedback::release_torso_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::rb::api::TorsoCommand_Feedback* released = _impl_.torso_command_feedback_;
  _impl_.torso_command_feedback_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::rb::api::TorsoCommand_Feedback* BodyComponentBasedCommand_Feedback::unsafe_arena_release_torso_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rb.api.BodyComponentBasedCommand.Feedback.torso_command_feedback)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::rb::api::TorsoCommand_Feedback* temp = _impl_.torso_command_feedback_;
  _impl_.torso_command_feedback_ = nullptr;
  return temp;
}
inline ::rb::api::TorsoCommand_Feedback* BodyComponentBasedCommand_Feedback::_internal_mutable_torso_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.torso_command_feedback_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::rb::api::TorsoCommand_Feedback>(GetArena());
    _impl_.torso_command_feedback_ = reinterpret_cast<::rb::api::TorsoCommand_Feedback*>(p);
  }
  return _impl_.torso_command_feedback_;
}
inline ::rb::api::TorsoCommand_Feedback* BodyComponentBasedCommand_Feedback::mutable_torso_command_feedback() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::rb::api::TorsoCommand_Feedback* _msg = _internal_mutable_torso_command_feedback();
  // @@protoc_insertion_point(field_mutable:rb.api.BodyComponentBasedCommand.Feedback.torso_command_feedback)
  return _msg;
}
inline void BodyComponentBasedCommand_Feedback::set_allocated_torso_command_feedback(::rb::api::TorsoCommand_Feedback* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.torso_command_feedback_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.torso_command_feedback_ = reinterpret_cast<::rb::api::TorsoCommand_Feedback*>(value);
  // @@protoc_insertion_point(field_set_allocated:rb.api.BodyComponentBasedCommand.Feedback.torso_command_feedback)
}

// -------------------------------------------------------------------

// BodyComponentBasedCommand

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace rb


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_rb_2fapi_2fbody_5fcomponent_5fbased_5fcommand_2eproto_2epb_2eh
