// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rb/api/control_manager_service.proto
#ifndef GRPC_rb_2fapi_2fcontrol_5fmanager_5fservice_2eproto__INCLUDED
#define GRPC_rb_2fapi_2fcontrol_5fmanager_5fservice_2eproto__INCLUDED

#include "rb/api/control_manager_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace rb {
namespace api {

class ControlManagerService final {
 public:
  static constexpr char const* service_full_name() {
    return "rb.api.ControlManagerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::rb::api::ControlManagerCommandResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ControlManagerCommandResponse>> AsyncControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ControlManagerCommandResponse>>(AsyncControlManagerCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ControlManagerCommandResponse>> PrepareAsyncControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ControlManagerCommandResponse>>(PrepareAsyncControlManagerCommandRaw(context, request, cq));
    }
    virtual ::grpc::Status CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::rb::api::CancelControlResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::CancelControlResponse>> AsyncCancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::CancelControlResponse>>(AsyncCancelControlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::CancelControlResponse>> PrepareAsyncCancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::CancelControlResponse>>(PrepareAsyncCancelControlRaw(context, request, cq));
    }
    virtual ::grpc::Status GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::rb::api::GetTimeScaleResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetTimeScaleResponse>> AsyncGetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetTimeScaleResponse>>(AsyncGetTimeScaleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetTimeScaleResponse>> PrepareAsyncGetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetTimeScaleResponse>>(PrepareAsyncGetTimeScaleRaw(context, request, cq));
    }
    virtual ::grpc::Status SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::rb::api::SetTimeScaleResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::SetTimeScaleResponse>> AsyncSetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::SetTimeScaleResponse>>(AsyncSetTimeScaleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::SetTimeScaleResponse>> PrepareAsyncSetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::SetTimeScaleResponse>>(PrepareAsyncSetTimeScaleRaw(context, request, cq));
    }
    virtual ::grpc::Status WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::rb::api::WaitForControlReadyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::WaitForControlReadyResponse>> AsyncWaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::WaitForControlReadyResponse>>(AsyncWaitForControlReadyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::WaitForControlReadyResponse>> PrepareAsyncWaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::WaitForControlReadyResponse>>(PrepareAsyncWaitForControlReadyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ControlManagerCommandResponse>* AsyncControlManagerCommandRaw(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ControlManagerCommandResponse>* PrepareAsyncControlManagerCommandRaw(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::CancelControlResponse>* AsyncCancelControlRaw(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::CancelControlResponse>* PrepareAsyncCancelControlRaw(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetTimeScaleResponse>* AsyncGetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetTimeScaleResponse>* PrepareAsyncGetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::SetTimeScaleResponse>* AsyncSetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::SetTimeScaleResponse>* PrepareAsyncSetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::WaitForControlReadyResponse>* AsyncWaitForControlReadyRaw(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::WaitForControlReadyResponse>* PrepareAsyncWaitForControlReadyRaw(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::rb::api::ControlManagerCommandResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ControlManagerCommandResponse>> AsyncControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ControlManagerCommandResponse>>(AsyncControlManagerCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ControlManagerCommandResponse>> PrepareAsyncControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ControlManagerCommandResponse>>(PrepareAsyncControlManagerCommandRaw(context, request, cq));
    }
    ::grpc::Status CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::rb::api::CancelControlResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::CancelControlResponse>> AsyncCancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::CancelControlResponse>>(AsyncCancelControlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::CancelControlResponse>> PrepareAsyncCancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::CancelControlResponse>>(PrepareAsyncCancelControlRaw(context, request, cq));
    }
    ::grpc::Status GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::rb::api::GetTimeScaleResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetTimeScaleResponse>> AsyncGetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetTimeScaleResponse>>(AsyncGetTimeScaleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetTimeScaleResponse>> PrepareAsyncGetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetTimeScaleResponse>>(PrepareAsyncGetTimeScaleRaw(context, request, cq));
    }
    ::grpc::Status SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::rb::api::SetTimeScaleResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::SetTimeScaleResponse>> AsyncSetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::SetTimeScaleResponse>>(AsyncSetTimeScaleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::SetTimeScaleResponse>> PrepareAsyncSetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::SetTimeScaleResponse>>(PrepareAsyncSetTimeScaleRaw(context, request, cq));
    }
    ::grpc::Status WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::rb::api::WaitForControlReadyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::WaitForControlReadyResponse>> AsyncWaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::WaitForControlReadyResponse>>(AsyncWaitForControlReadyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::WaitForControlReadyResponse>> PrepareAsyncWaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::WaitForControlReadyResponse>>(PrepareAsyncWaitForControlReadyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response, std::function<void(::grpc::Status)>) override;
      void ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response, std::function<void(::grpc::Status)>) override;
      void CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response, std::function<void(::grpc::Status)>) override;
      void GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response, std::function<void(::grpc::Status)>) override;
      void SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response, std::function<void(::grpc::Status)>) override;
      void WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rb::api::ControlManagerCommandResponse>* AsyncControlManagerCommandRaw(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::ControlManagerCommandResponse>* PrepareAsyncControlManagerCommandRaw(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::CancelControlResponse>* AsyncCancelControlRaw(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::CancelControlResponse>* PrepareAsyncCancelControlRaw(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetTimeScaleResponse>* AsyncGetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetTimeScaleResponse>* PrepareAsyncGetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::SetTimeScaleResponse>* AsyncSetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::SetTimeScaleResponse>* PrepareAsyncSetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::WaitForControlReadyResponse>* AsyncWaitForControlReadyRaw(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::WaitForControlReadyResponse>* PrepareAsyncWaitForControlReadyRaw(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ControlManagerCommand_;
    const ::grpc::internal::RpcMethod rpcmethod_CancelControl_;
    const ::grpc::internal::RpcMethod rpcmethod_GetTimeScale_;
    const ::grpc::internal::RpcMethod rpcmethod_SetTimeScale_;
    const ::grpc::internal::RpcMethod rpcmethod_WaitForControlReady_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ControlManagerCommand(::grpc::ServerContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response);
    virtual ::grpc::Status CancelControl(::grpc::ServerContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response);
    virtual ::grpc::Status GetTimeScale(::grpc::ServerContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response);
    virtual ::grpc::Status SetTimeScale(::grpc::ServerContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response);
    virtual ::grpc::Status WaitForControlReady(::grpc::ServerContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ControlManagerCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ControlManagerCommand() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ControlManagerCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlManagerCommand(::grpc::ServerContext* /*context*/, const ::rb::api::ControlManagerCommandRequest* /*request*/, ::rb::api::ControlManagerCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControlManagerCommand(::grpc::ServerContext* context, ::rb::api::ControlManagerCommandRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::ControlManagerCommandResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CancelControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CancelControl() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CancelControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelControl(::grpc::ServerContext* /*context*/, const ::rb::api::CancelControlRequest* /*request*/, ::rb::api::CancelControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelControl(::grpc::ServerContext* context, ::rb::api::CancelControlRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::CancelControlResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetTimeScale() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::GetTimeScaleRequest* /*request*/, ::rb::api::GetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTimeScale(::grpc::ServerContext* context, ::rb::api::GetTimeScaleRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::GetTimeScaleResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetTimeScale() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_SetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::SetTimeScaleRequest* /*request*/, ::rb::api::SetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetTimeScale(::grpc::ServerContext* context, ::rb::api::SetTimeScaleRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::SetTimeScaleResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WaitForControlReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WaitForControlReady() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_WaitForControlReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WaitForControlReady(::grpc::ServerContext* /*context*/, const ::rb::api::WaitForControlReadyRequest* /*request*/, ::rb::api::WaitForControlReadyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWaitForControlReady(::grpc::ServerContext* context, ::rb::api::WaitForControlReadyRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::WaitForControlReadyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ControlManagerCommand<WithAsyncMethod_CancelControl<WithAsyncMethod_GetTimeScale<WithAsyncMethod_SetTimeScale<WithAsyncMethod_WaitForControlReady<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ControlManagerCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ControlManagerCommand() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::ControlManagerCommandRequest, ::rb::api::ControlManagerCommandResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response) { return this->ControlManagerCommand(context, request, response); }));}
    void SetMessageAllocatorFor_ControlManagerCommand(
        ::grpc::MessageAllocator< ::rb::api::ControlManagerCommandRequest, ::rb::api::ControlManagerCommandResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::ControlManagerCommandRequest, ::rb::api::ControlManagerCommandResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ControlManagerCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlManagerCommand(::grpc::ServerContext* /*context*/, const ::rb::api::ControlManagerCommandRequest* /*request*/, ::rb::api::ControlManagerCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ControlManagerCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::ControlManagerCommandRequest* /*request*/, ::rb::api::ControlManagerCommandResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CancelControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CancelControl() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::CancelControlRequest, ::rb::api::CancelControlResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response) { return this->CancelControl(context, request, response); }));}
    void SetMessageAllocatorFor_CancelControl(
        ::grpc::MessageAllocator< ::rb::api::CancelControlRequest, ::rb::api::CancelControlResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::CancelControlRequest, ::rb::api::CancelControlResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CancelControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelControl(::grpc::ServerContext* /*context*/, const ::rb::api::CancelControlRequest* /*request*/, ::rb::api::CancelControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelControl(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::CancelControlRequest* /*request*/, ::rb::api::CancelControlResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetTimeScale() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::GetTimeScaleRequest, ::rb::api::GetTimeScaleResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response) { return this->GetTimeScale(context, request, response); }));}
    void SetMessageAllocatorFor_GetTimeScale(
        ::grpc::MessageAllocator< ::rb::api::GetTimeScaleRequest, ::rb::api::GetTimeScaleResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::GetTimeScaleRequest, ::rb::api::GetTimeScaleResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::GetTimeScaleRequest* /*request*/, ::rb::api::GetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTimeScale(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::GetTimeScaleRequest* /*request*/, ::rb::api::GetTimeScaleResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetTimeScale() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::SetTimeScaleRequest, ::rb::api::SetTimeScaleResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response) { return this->SetTimeScale(context, request, response); }));}
    void SetMessageAllocatorFor_SetTimeScale(
        ::grpc::MessageAllocator< ::rb::api::SetTimeScaleRequest, ::rb::api::SetTimeScaleResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::SetTimeScaleRequest, ::rb::api::SetTimeScaleResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::SetTimeScaleRequest* /*request*/, ::rb::api::SetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetTimeScale(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::SetTimeScaleRequest* /*request*/, ::rb::api::SetTimeScaleResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_WaitForControlReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_WaitForControlReady() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::WaitForControlReadyRequest, ::rb::api::WaitForControlReadyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response) { return this->WaitForControlReady(context, request, response); }));}
    void SetMessageAllocatorFor_WaitForControlReady(
        ::grpc::MessageAllocator< ::rb::api::WaitForControlReadyRequest, ::rb::api::WaitForControlReadyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::WaitForControlReadyRequest, ::rb::api::WaitForControlReadyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_WaitForControlReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WaitForControlReady(::grpc::ServerContext* /*context*/, const ::rb::api::WaitForControlReadyRequest* /*request*/, ::rb::api::WaitForControlReadyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WaitForControlReady(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::WaitForControlReadyRequest* /*request*/, ::rb::api::WaitForControlReadyResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ControlManagerCommand<WithCallbackMethod_CancelControl<WithCallbackMethod_GetTimeScale<WithCallbackMethod_SetTimeScale<WithCallbackMethod_WaitForControlReady<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ControlManagerCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ControlManagerCommand() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ControlManagerCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlManagerCommand(::grpc::ServerContext* /*context*/, const ::rb::api::ControlManagerCommandRequest* /*request*/, ::rb::api::ControlManagerCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CancelControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CancelControl() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CancelControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelControl(::grpc::ServerContext* /*context*/, const ::rb::api::CancelControlRequest* /*request*/, ::rb::api::CancelControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetTimeScale() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::GetTimeScaleRequest* /*request*/, ::rb::api::GetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetTimeScale() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_SetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::SetTimeScaleRequest* /*request*/, ::rb::api::SetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WaitForControlReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WaitForControlReady() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_WaitForControlReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WaitForControlReady(::grpc::ServerContext* /*context*/, const ::rb::api::WaitForControlReadyRequest* /*request*/, ::rb::api::WaitForControlReadyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ControlManagerCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ControlManagerCommand() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ControlManagerCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlManagerCommand(::grpc::ServerContext* /*context*/, const ::rb::api::ControlManagerCommandRequest* /*request*/, ::rb::api::ControlManagerCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControlManagerCommand(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CancelControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CancelControl() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CancelControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelControl(::grpc::ServerContext* /*context*/, const ::rb::api::CancelControlRequest* /*request*/, ::rb::api::CancelControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelControl(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetTimeScale() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::GetTimeScaleRequest* /*request*/, ::rb::api::GetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTimeScale(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetTimeScale() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_SetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::SetTimeScaleRequest* /*request*/, ::rb::api::SetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetTimeScale(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WaitForControlReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WaitForControlReady() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_WaitForControlReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WaitForControlReady(::grpc::ServerContext* /*context*/, const ::rb::api::WaitForControlReadyRequest* /*request*/, ::rb::api::WaitForControlReadyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWaitForControlReady(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ControlManagerCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ControlManagerCommand() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ControlManagerCommand(context, request, response); }));
    }
    ~WithRawCallbackMethod_ControlManagerCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlManagerCommand(::grpc::ServerContext* /*context*/, const ::rb::api::ControlManagerCommandRequest* /*request*/, ::rb::api::ControlManagerCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ControlManagerCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CancelControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CancelControl() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CancelControl(context, request, response); }));
    }
    ~WithRawCallbackMethod_CancelControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelControl(::grpc::ServerContext* /*context*/, const ::rb::api::CancelControlRequest* /*request*/, ::rb::api::CancelControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelControl(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetTimeScale() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetTimeScale(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::GetTimeScaleRequest* /*request*/, ::rb::api::GetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTimeScale(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetTimeScale() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetTimeScale(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::SetTimeScaleRequest* /*request*/, ::rb::api::SetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetTimeScale(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_WaitForControlReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_WaitForControlReady() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->WaitForControlReady(context, request, response); }));
    }
    ~WithRawCallbackMethod_WaitForControlReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WaitForControlReady(::grpc::ServerContext* /*context*/, const ::rb::api::WaitForControlReadyRequest* /*request*/, ::rb::api::WaitForControlReadyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WaitForControlReady(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ControlManagerCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ControlManagerCommand() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::ControlManagerCommandRequest, ::rb::api::ControlManagerCommandResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::ControlManagerCommandRequest, ::rb::api::ControlManagerCommandResponse>* streamer) {
                       return this->StreamedControlManagerCommand(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ControlManagerCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ControlManagerCommand(::grpc::ServerContext* /*context*/, const ::rb::api::ControlManagerCommandRequest* /*request*/, ::rb::api::ControlManagerCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedControlManagerCommand(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::ControlManagerCommandRequest,::rb::api::ControlManagerCommandResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CancelControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CancelControl() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::CancelControlRequest, ::rb::api::CancelControlResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::CancelControlRequest, ::rb::api::CancelControlResponse>* streamer) {
                       return this->StreamedCancelControl(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CancelControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CancelControl(::grpc::ServerContext* /*context*/, const ::rb::api::CancelControlRequest* /*request*/, ::rb::api::CancelControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCancelControl(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::CancelControlRequest,::rb::api::CancelControlResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetTimeScale() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::GetTimeScaleRequest, ::rb::api::GetTimeScaleResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::GetTimeScaleRequest, ::rb::api::GetTimeScaleResponse>* streamer) {
                       return this->StreamedGetTimeScale(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::GetTimeScaleRequest* /*request*/, ::rb::api::GetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetTimeScale(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::GetTimeScaleRequest,::rb::api::GetTimeScaleResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetTimeScale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetTimeScale() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::SetTimeScaleRequest, ::rb::api::SetTimeScaleResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::SetTimeScaleRequest, ::rb::api::SetTimeScaleResponse>* streamer) {
                       return this->StreamedSetTimeScale(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetTimeScale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetTimeScale(::grpc::ServerContext* /*context*/, const ::rb::api::SetTimeScaleRequest* /*request*/, ::rb::api::SetTimeScaleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetTimeScale(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::SetTimeScaleRequest,::rb::api::SetTimeScaleResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_WaitForControlReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_WaitForControlReady() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::WaitForControlReadyRequest, ::rb::api::WaitForControlReadyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::WaitForControlReadyRequest, ::rb::api::WaitForControlReadyResponse>* streamer) {
                       return this->StreamedWaitForControlReady(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_WaitForControlReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WaitForControlReady(::grpc::ServerContext* /*context*/, const ::rb::api::WaitForControlReadyRequest* /*request*/, ::rb::api::WaitForControlReadyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWaitForControlReady(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::WaitForControlReadyRequest,::rb::api::WaitForControlReadyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ControlManagerCommand<WithStreamedUnaryMethod_CancelControl<WithStreamedUnaryMethod_GetTimeScale<WithStreamedUnaryMethod_SetTimeScale<WithStreamedUnaryMethod_WaitForControlReady<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ControlManagerCommand<WithStreamedUnaryMethod_CancelControl<WithStreamedUnaryMethod_GetTimeScale<WithStreamedUnaryMethod_SetTimeScale<WithStreamedUnaryMethod_WaitForControlReady<Service > > > > > StreamedService;
};

}  // namespace api
}  // namespace rb


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_rb_2fapi_2fcontrol_5fmanager_5fservice_2eproto__INCLUDED
