// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rb/api/control_manager_service.proto

#include "rb/api/control_manager_service.pb.h"
#include "rb/api/control_manager_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rb {
namespace api {

static const char* ControlManagerService_method_names[] = {
  "/rb.api.ControlManagerService/ControlManagerCommand",
  "/rb.api.ControlManagerService/CancelControl",
  "/rb.api.ControlManagerService/GetTimeScale",
  "/rb.api.ControlManagerService/SetTimeScale",
  "/rb.api.ControlManagerService/WaitForControlReady",
};

std::unique_ptr< ControlManagerService::Stub> ControlManagerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ControlManagerService::Stub> stub(new ControlManagerService::Stub(channel, options));
  return stub;
}

ControlManagerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ControlManagerCommand_(ControlManagerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CancelControl_(ControlManagerService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTimeScale_(ControlManagerService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetTimeScale_(ControlManagerService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WaitForControlReady_(ControlManagerService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ControlManagerService::Stub::ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::rb::api::ControlManagerCommandResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rb::api::ControlManagerCommandRequest, ::rb::api::ControlManagerCommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ControlManagerCommand_, context, request, response);
}

void ControlManagerService::Stub::async::ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rb::api::ControlManagerCommandRequest, ::rb::api::ControlManagerCommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ControlManagerCommand_, context, request, response, std::move(f));
}

void ControlManagerService::Stub::async::ControlManagerCommand(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ControlManagerCommand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rb::api::ControlManagerCommandResponse>* ControlManagerService::Stub::PrepareAsyncControlManagerCommandRaw(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rb::api::ControlManagerCommandResponse, ::rb::api::ControlManagerCommandRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ControlManagerCommand_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rb::api::ControlManagerCommandResponse>* ControlManagerService::Stub::AsyncControlManagerCommandRaw(::grpc::ClientContext* context, const ::rb::api::ControlManagerCommandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncControlManagerCommandRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlManagerService::Stub::CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::rb::api::CancelControlResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rb::api::CancelControlRequest, ::rb::api::CancelControlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CancelControl_, context, request, response);
}

void ControlManagerService::Stub::async::CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rb::api::CancelControlRequest, ::rb::api::CancelControlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelControl_, context, request, response, std::move(f));
}

void ControlManagerService::Stub::async::CancelControl(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelControl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rb::api::CancelControlResponse>* ControlManagerService::Stub::PrepareAsyncCancelControlRaw(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rb::api::CancelControlResponse, ::rb::api::CancelControlRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CancelControl_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rb::api::CancelControlResponse>* ControlManagerService::Stub::AsyncCancelControlRaw(::grpc::ClientContext* context, const ::rb::api::CancelControlRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCancelControlRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlManagerService::Stub::GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::rb::api::GetTimeScaleResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rb::api::GetTimeScaleRequest, ::rb::api::GetTimeScaleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTimeScale_, context, request, response);
}

void ControlManagerService::Stub::async::GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rb::api::GetTimeScaleRequest, ::rb::api::GetTimeScaleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTimeScale_, context, request, response, std::move(f));
}

void ControlManagerService::Stub::async::GetTimeScale(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTimeScale_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rb::api::GetTimeScaleResponse>* ControlManagerService::Stub::PrepareAsyncGetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rb::api::GetTimeScaleResponse, ::rb::api::GetTimeScaleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTimeScale_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rb::api::GetTimeScaleResponse>* ControlManagerService::Stub::AsyncGetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::GetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTimeScaleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlManagerService::Stub::SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::rb::api::SetTimeScaleResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rb::api::SetTimeScaleRequest, ::rb::api::SetTimeScaleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetTimeScale_, context, request, response);
}

void ControlManagerService::Stub::async::SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rb::api::SetTimeScaleRequest, ::rb::api::SetTimeScaleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTimeScale_, context, request, response, std::move(f));
}

void ControlManagerService::Stub::async::SetTimeScale(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTimeScale_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rb::api::SetTimeScaleResponse>* ControlManagerService::Stub::PrepareAsyncSetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rb::api::SetTimeScaleResponse, ::rb::api::SetTimeScaleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetTimeScale_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rb::api::SetTimeScaleResponse>* ControlManagerService::Stub::AsyncSetTimeScaleRaw(::grpc::ClientContext* context, const ::rb::api::SetTimeScaleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetTimeScaleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlManagerService::Stub::WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::rb::api::WaitForControlReadyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rb::api::WaitForControlReadyRequest, ::rb::api::WaitForControlReadyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WaitForControlReady_, context, request, response);
}

void ControlManagerService::Stub::async::WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rb::api::WaitForControlReadyRequest, ::rb::api::WaitForControlReadyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WaitForControlReady_, context, request, response, std::move(f));
}

void ControlManagerService::Stub::async::WaitForControlReady(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WaitForControlReady_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rb::api::WaitForControlReadyResponse>* ControlManagerService::Stub::PrepareAsyncWaitForControlReadyRaw(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rb::api::WaitForControlReadyResponse, ::rb::api::WaitForControlReadyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WaitForControlReady_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rb::api::WaitForControlReadyResponse>* ControlManagerService::Stub::AsyncWaitForControlReadyRaw(::grpc::ClientContext* context, const ::rb::api::WaitForControlReadyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWaitForControlReadyRaw(context, request, cq);
  result->StartCall();
  return result;
}

ControlManagerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlManagerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlManagerService::Service, ::rb::api::ControlManagerCommandRequest, ::rb::api::ControlManagerCommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rb::api::ControlManagerCommandRequest* req,
             ::rb::api::ControlManagerCommandResponse* resp) {
               return service->ControlManagerCommand(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlManagerService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlManagerService::Service, ::rb::api::CancelControlRequest, ::rb::api::CancelControlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rb::api::CancelControlRequest* req,
             ::rb::api::CancelControlResponse* resp) {
               return service->CancelControl(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlManagerService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlManagerService::Service, ::rb::api::GetTimeScaleRequest, ::rb::api::GetTimeScaleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rb::api::GetTimeScaleRequest* req,
             ::rb::api::GetTimeScaleResponse* resp) {
               return service->GetTimeScale(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlManagerService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlManagerService::Service, ::rb::api::SetTimeScaleRequest, ::rb::api::SetTimeScaleResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rb::api::SetTimeScaleRequest* req,
             ::rb::api::SetTimeScaleResponse* resp) {
               return service->SetTimeScale(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlManagerService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlManagerService::Service, ::rb::api::WaitForControlReadyRequest, ::rb::api::WaitForControlReadyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlManagerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rb::api::WaitForControlReadyRequest* req,
             ::rb::api::WaitForControlReadyResponse* resp) {
               return service->WaitForControlReady(ctx, req, resp);
             }, this)));
}

ControlManagerService::Service::~Service() {
}

::grpc::Status ControlManagerService::Service::ControlManagerCommand(::grpc::ServerContext* context, const ::rb::api::ControlManagerCommandRequest* request, ::rb::api::ControlManagerCommandResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlManagerService::Service::CancelControl(::grpc::ServerContext* context, const ::rb::api::CancelControlRequest* request, ::rb::api::CancelControlResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlManagerService::Service::GetTimeScale(::grpc::ServerContext* context, const ::rb::api::GetTimeScaleRequest* request, ::rb::api::GetTimeScaleResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlManagerService::Service::SetTimeScale(::grpc::ServerContext* context, const ::rb::api::SetTimeScaleRequest* request, ::rb::api::SetTimeScaleResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlManagerService::Service::WaitForControlReady(::grpc::ServerContext* context, const ::rb::api::WaitForControlReadyRequest* request, ::rb::api::WaitForControlReadyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rb
}  // namespace api

