// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rb/api/gamepad_service.proto
#ifndef GRPC_rb_2fapi_2fgamepad_5fservice_2eproto__INCLUDED
#define GRPC_rb_2fapi_2fgamepad_5fservice_2eproto__INCLUDED

#include "rb/api/gamepad_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace rb {
namespace api {

class GamepadService final {
 public:
  static constexpr char const* service_full_name() {
    return "rb.api.GamepadService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::rb::api::Gamepad>> UploadGamepadData(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::rb::api::Gamepad>>(UploadGamepadDataRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rb::api::Gamepad>> AsyncUploadGamepadData(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rb::api::Gamepad>>(AsyncUploadGamepadDataRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rb::api::Gamepad>> PrepareAsyncUploadGamepadData(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rb::api::Gamepad>>(PrepareAsyncUploadGamepadDataRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void UploadGamepadData(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::ClientWriteReactor< ::rb::api::Gamepad>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::rb::api::Gamepad>* UploadGamepadDataRaw(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::rb::api::Gamepad>* AsyncUploadGamepadDataRaw(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::rb::api::Gamepad>* PrepareAsyncUploadGamepadDataRaw(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::rb::api::Gamepad>> UploadGamepadData(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::rb::api::Gamepad>>(UploadGamepadDataRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::rb::api::Gamepad>> AsyncUploadGamepadData(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::rb::api::Gamepad>>(AsyncUploadGamepadDataRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::rb::api::Gamepad>> PrepareAsyncUploadGamepadData(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::rb::api::Gamepad>>(PrepareAsyncUploadGamepadDataRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UploadGamepadData(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::ClientWriteReactor< ::rb::api::Gamepad>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::rb::api::Gamepad>* UploadGamepadDataRaw(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response) override;
    ::grpc::ClientAsyncWriter< ::rb::api::Gamepad>* AsyncUploadGamepadDataRaw(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::rb::api::Gamepad>* PrepareAsyncUploadGamepadDataRaw(::grpc::ClientContext* context, ::rb::api::UploadGamepadDataResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UploadGamepadData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status UploadGamepadData(::grpc::ServerContext* context, ::grpc::ServerReader< ::rb::api::Gamepad>* reader, ::rb::api::UploadGamepadDataResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UploadGamepadData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UploadGamepadData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UploadGamepadData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadGamepadData(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rb::api::Gamepad>* /*reader*/, ::rb::api::UploadGamepadDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadGamepadData(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::rb::api::UploadGamepadDataResponse, ::rb::api::Gamepad>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UploadGamepadData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UploadGamepadData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UploadGamepadData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::rb::api::Gamepad, ::rb::api::UploadGamepadDataResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::rb::api::UploadGamepadDataResponse* response) { return this->UploadGamepadData(context, response); }));
    }
    ~WithCallbackMethod_UploadGamepadData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadGamepadData(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rb::api::Gamepad>* /*reader*/, ::rb::api::UploadGamepadDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::rb::api::Gamepad>* UploadGamepadData(
      ::grpc::CallbackServerContext* /*context*/, ::rb::api::UploadGamepadDataResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UploadGamepadData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UploadGamepadData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UploadGamepadData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UploadGamepadData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadGamepadData(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rb::api::Gamepad>* /*reader*/, ::rb::api::UploadGamepadDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UploadGamepadData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UploadGamepadData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UploadGamepadData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadGamepadData(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rb::api::Gamepad>* /*reader*/, ::rb::api::UploadGamepadDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadGamepadData(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UploadGamepadData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UploadGamepadData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->UploadGamepadData(context, response); }));
    }
    ~WithRawCallbackMethod_UploadGamepadData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadGamepadData(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rb::api::Gamepad>* /*reader*/, ::rb::api::UploadGamepadDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* UploadGamepadData(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace api
}  // namespace rb


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_rb_2fapi_2fgamepad_5fservice_2eproto__INCLUDED
