// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rb/api/gripper_command_service.proto
#ifndef GRPC_rb_2fapi_2fgripper_5fcommand_5fservice_2eproto__INCLUDED
#define GRPC_rb_2fapi_2fgripper_5fcommand_5fservice_2eproto__INCLUDED

#include "rb/api/gripper_command_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace rb {
namespace api {

class GripperCommandService final {
 public:
  static constexpr char const* service_full_name() {
    return "rb.api.GripperCommandService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::rb::api::GripperInitializationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperInitializationResponse>> AsyncGripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperInitializationResponse>>(AsyncGripperInitializationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperInitializationResponse>> PrepareAsyncGripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperInitializationResponse>>(PrepareAsyncGripperInitializationRaw(context, request, cq));
    }
    // Joint command
    virtual ::grpc::Status GripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::rb::api::GripperMoveResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperMoveResponse>> AsyncGripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperMoveResponse>>(AsyncGripperMoveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperMoveResponse>> PrepareAsyncGripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperMoveResponse>>(PrepareAsyncGripperMoveRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest* request, ::rb::api::GripperInitializationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest* request, ::rb::api::GripperInitializationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Joint command
      virtual void GripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest* request, ::rb::api::GripperMoveResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest* request, ::rb::api::GripperMoveResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperInitializationResponse>* AsyncGripperInitializationRaw(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperInitializationResponse>* PrepareAsyncGripperInitializationRaw(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperMoveResponse>* AsyncGripperMoveRaw(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GripperMoveResponse>* PrepareAsyncGripperMoveRaw(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::rb::api::GripperInitializationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GripperInitializationResponse>> AsyncGripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GripperInitializationResponse>>(AsyncGripperInitializationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GripperInitializationResponse>> PrepareAsyncGripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GripperInitializationResponse>>(PrepareAsyncGripperInitializationRaw(context, request, cq));
    }
    ::grpc::Status GripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::rb::api::GripperMoveResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GripperMoveResponse>> AsyncGripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GripperMoveResponse>>(AsyncGripperMoveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GripperMoveResponse>> PrepareAsyncGripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GripperMoveResponse>>(PrepareAsyncGripperMoveRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest* request, ::rb::api::GripperInitializationResponse* response, std::function<void(::grpc::Status)>) override;
      void GripperInitialization(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest* request, ::rb::api::GripperInitializationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest* request, ::rb::api::GripperMoveResponse* response, std::function<void(::grpc::Status)>) override;
      void GripperMove(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest* request, ::rb::api::GripperMoveResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rb::api::GripperInitializationResponse>* AsyncGripperInitializationRaw(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GripperInitializationResponse>* PrepareAsyncGripperInitializationRaw(::grpc::ClientContext* context, const ::rb::api::GripperInitializationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GripperMoveResponse>* AsyncGripperMoveRaw(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GripperMoveResponse>* PrepareAsyncGripperMoveRaw(::grpc::ClientContext* context, const ::rb::api::GripperMoveRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GripperInitialization_;
    const ::grpc::internal::RpcMethod rpcmethod_GripperMove_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GripperInitialization(::grpc::ServerContext* context, const ::rb::api::GripperInitializationRequest* request, ::rb::api::GripperInitializationResponse* response);
    // Joint command
    virtual ::grpc::Status GripperMove(::grpc::ServerContext* context, const ::rb::api::GripperMoveRequest* request, ::rb::api::GripperMoveResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GripperInitialization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GripperInitialization() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GripperInitialization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperInitialization(::grpc::ServerContext* /*context*/, const ::rb::api::GripperInitializationRequest* /*request*/, ::rb::api::GripperInitializationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGripperInitialization(::grpc::ServerContext* context, ::rb::api::GripperInitializationRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::GripperInitializationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GripperMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GripperMove() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GripperMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperMove(::grpc::ServerContext* /*context*/, const ::rb::api::GripperMoveRequest* /*request*/, ::rb::api::GripperMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGripperMove(::grpc::ServerContext* context, ::rb::api::GripperMoveRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::GripperMoveResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GripperInitialization<WithAsyncMethod_GripperMove<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GripperInitialization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GripperInitialization() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::GripperInitializationRequest, ::rb::api::GripperInitializationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::GripperInitializationRequest* request, ::rb::api::GripperInitializationResponse* response) { return this->GripperInitialization(context, request, response); }));}
    void SetMessageAllocatorFor_GripperInitialization(
        ::grpc::MessageAllocator< ::rb::api::GripperInitializationRequest, ::rb::api::GripperInitializationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::GripperInitializationRequest, ::rb::api::GripperInitializationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GripperInitialization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperInitialization(::grpc::ServerContext* /*context*/, const ::rb::api::GripperInitializationRequest* /*request*/, ::rb::api::GripperInitializationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GripperInitialization(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::GripperInitializationRequest* /*request*/, ::rb::api::GripperInitializationResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GripperMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GripperMove() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::GripperMoveRequest, ::rb::api::GripperMoveResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::GripperMoveRequest* request, ::rb::api::GripperMoveResponse* response) { return this->GripperMove(context, request, response); }));}
    void SetMessageAllocatorFor_GripperMove(
        ::grpc::MessageAllocator< ::rb::api::GripperMoveRequest, ::rb::api::GripperMoveResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::GripperMoveRequest, ::rb::api::GripperMoveResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GripperMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperMove(::grpc::ServerContext* /*context*/, const ::rb::api::GripperMoveRequest* /*request*/, ::rb::api::GripperMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GripperMove(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::GripperMoveRequest* /*request*/, ::rb::api::GripperMoveResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GripperInitialization<WithCallbackMethod_GripperMove<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GripperInitialization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GripperInitialization() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GripperInitialization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperInitialization(::grpc::ServerContext* /*context*/, const ::rb::api::GripperInitializationRequest* /*request*/, ::rb::api::GripperInitializationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GripperMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GripperMove() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GripperMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperMove(::grpc::ServerContext* /*context*/, const ::rb::api::GripperMoveRequest* /*request*/, ::rb::api::GripperMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GripperInitialization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GripperInitialization() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GripperInitialization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperInitialization(::grpc::ServerContext* /*context*/, const ::rb::api::GripperInitializationRequest* /*request*/, ::rb::api::GripperInitializationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGripperInitialization(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GripperMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GripperMove() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GripperMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperMove(::grpc::ServerContext* /*context*/, const ::rb::api::GripperMoveRequest* /*request*/, ::rb::api::GripperMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGripperMove(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GripperInitialization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GripperInitialization() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GripperInitialization(context, request, response); }));
    }
    ~WithRawCallbackMethod_GripperInitialization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperInitialization(::grpc::ServerContext* /*context*/, const ::rb::api::GripperInitializationRequest* /*request*/, ::rb::api::GripperInitializationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GripperInitialization(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GripperMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GripperMove() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GripperMove(context, request, response); }));
    }
    ~WithRawCallbackMethod_GripperMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GripperMove(::grpc::ServerContext* /*context*/, const ::rb::api::GripperMoveRequest* /*request*/, ::rb::api::GripperMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GripperMove(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GripperInitialization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GripperInitialization() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::GripperInitializationRequest, ::rb::api::GripperInitializationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::GripperInitializationRequest, ::rb::api::GripperInitializationResponse>* streamer) {
                       return this->StreamedGripperInitialization(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GripperInitialization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GripperInitialization(::grpc::ServerContext* /*context*/, const ::rb::api::GripperInitializationRequest* /*request*/, ::rb::api::GripperInitializationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGripperInitialization(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::GripperInitializationRequest,::rb::api::GripperInitializationResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GripperMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GripperMove() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::GripperMoveRequest, ::rb::api::GripperMoveResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::GripperMoveRequest, ::rb::api::GripperMoveResponse>* streamer) {
                       return this->StreamedGripperMove(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GripperMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GripperMove(::grpc::ServerContext* /*context*/, const ::rb::api::GripperMoveRequest* /*request*/, ::rb::api::GripperMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGripperMove(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::GripperMoveRequest,::rb::api::GripperMoveResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GripperInitialization<WithStreamedUnaryMethod_GripperMove<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GripperInitialization<WithStreamedUnaryMethod_GripperMove<Service > > StreamedService;
};

}  // namespace api
}  // namespace rb


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_rb_2fapi_2fgripper_5fcommand_5fservice_2eproto__INCLUDED
