// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rb/api/header.proto
// Protobuf C++ Version: 5.27.0

#include "rb/api/header.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rb {
namespace api {

inline constexpr CommonError::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{static_cast< ::rb::api::CommonError_Code >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CommonError::CommonError(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CommonErrorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommonErrorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommonErrorDefaultTypeInternal() {}
  union {
    CommonError _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommonErrorDefaultTypeInternal _CommonError_default_instance_;

inline constexpr RequestHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        request_timestamp_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR RequestHeader::RequestHeader(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestHeaderDefaultTypeInternal() {}
  union {
    RequestHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestHeaderDefaultTypeInternal _RequestHeader_default_instance_;

inline constexpr ResponseHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        request_header_{nullptr},
        request_received_timestamp_{nullptr},
        response_timestamp_{nullptr},
        error_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseHeader::ResponseHeader(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ResponseHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseHeaderDefaultTypeInternal() {}
  union {
    ResponseHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseHeaderDefaultTypeInternal _ResponseHeader_default_instance_;
}  // namespace api
}  // namespace rb
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_rb_2fapi_2fheader_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rb_2fapi_2fheader_2eproto = nullptr;
const ::uint32_t
    TableStruct_rb_2fapi_2fheader_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::rb::api::RequestHeader, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RequestHeader, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::RequestHeader, _impl_.request_timestamp_),
        0,
        PROTOBUF_FIELD_OFFSET(::rb::api::ResponseHeader, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rb::api::ResponseHeader, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::ResponseHeader, _impl_.request_header_),
        PROTOBUF_FIELD_OFFSET(::rb::api::ResponseHeader, _impl_.request_received_timestamp_),
        PROTOBUF_FIELD_OFFSET(::rb::api::ResponseHeader, _impl_.response_timestamp_),
        PROTOBUF_FIELD_OFFSET(::rb::api::ResponseHeader, _impl_.error_),
        0,
        1,
        2,
        3,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::rb::api::CommonError, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::CommonError, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::rb::api::CommonError, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::rb::api::RequestHeader)},
        {10, 22, -1, sizeof(::rb::api::ResponseHeader)},
        {26, -1, -1, sizeof(::rb::api::CommonError)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::rb::api::_RequestHeader_default_instance_._instance,
    &::rb::api::_ResponseHeader_default_instance_._instance,
    &::rb::api::_CommonError_default_instance_._instance,
};
const char descriptor_table_protodef_rb_2fapi_2fheader_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023rb/api/header.proto\022\006rb.api\032\037google/pr"
    "otobuf/timestamp.proto\"F\n\rRequestHeader\022"
    "5\n\021request_timestamp\030\001 \001(\0132\032.google.prot"
    "obuf.Timestamp\"\333\001\n\016ResponseHeader\022-\n\016req"
    "uest_header\030\001 \001(\0132\025.rb.api.RequestHeader"
    "\022>\n\032request_received_timestamp\030\002 \001(\0132\032.g"
    "oogle.protobuf.Timestamp\0226\n\022response_tim"
    "estamp\030\003 \001(\0132\032.google.protobuf.Timestamp"
    "\022\"\n\005error\030\004 \001(\0132\023.rb.api.CommonError\"\253\001\n"
    "\013CommonError\022&\n\004code\030\001 \001(\0162\030.rb.api.Comm"
    "onError.Code\022\017\n\007message\030\002 \001(\t\"c\n\004Code\022\024\n"
    "\020CODE_UNSPECIFIED\020\000\022\013\n\007CODE_OK\020\001\022\036\n\032CODE"
    "_INTERNAL_SERVER_ERROR\020\002\022\030\n\024CODE_INVALID"
    "_REQUEST\020\003b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_rb_2fapi_2fheader_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_rb_2fapi_2fheader_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rb_2fapi_2fheader_2eproto = {
    false,
    false,
    538,
    descriptor_table_protodef_rb_2fapi_2fheader_2eproto,
    "rb/api/header.proto",
    &descriptor_table_rb_2fapi_2fheader_2eproto_once,
    descriptor_table_rb_2fapi_2fheader_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_rb_2fapi_2fheader_2eproto::offsets,
    file_level_enum_descriptors_rb_2fapi_2fheader_2eproto,
    file_level_service_descriptors_rb_2fapi_2fheader_2eproto,
};
namespace rb {
namespace api {
const ::google::protobuf::EnumDescriptor* CommonError_Code_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rb_2fapi_2fheader_2eproto);
  return file_level_enum_descriptors_rb_2fapi_2fheader_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CommonError_Code_internal_data_[] = {
    262144u, 0u, };
bool CommonError_Code_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr CommonError_Code CommonError::CODE_UNSPECIFIED;
constexpr CommonError_Code CommonError::CODE_OK;
constexpr CommonError_Code CommonError::CODE_INTERNAL_SERVER_ERROR;
constexpr CommonError_Code CommonError::CODE_INVALID_REQUEST;
constexpr CommonError_Code CommonError::Code_MIN;
constexpr CommonError_Code CommonError::Code_MAX;
constexpr int CommonError::Code_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class RequestHeader::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RequestHeader>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_._has_bits_);
};

void RequestHeader::clear_request_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_timestamp_ != nullptr) _impl_.request_timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
RequestHeader::RequestHeader(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.RequestHeader)
}
inline PROTOBUF_NDEBUG_INLINE RequestHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::RequestHeader& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

RequestHeader::RequestHeader(
    ::google::protobuf::Arena* arena,
    const RequestHeader& from)
    : ::google::protobuf::Message(arena) {
  RequestHeader* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.request_timestamp_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.request_timestamp_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:rb.api.RequestHeader)
}
inline PROTOBUF_NDEBUG_INLINE RequestHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RequestHeader::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.request_timestamp_ = {};
}
RequestHeader::~RequestHeader() {
  // @@protoc_insertion_point(destructor:rb.api.RequestHeader)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestHeader::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.request_timestamp_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RequestHeader::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_._cached_size_),
              false,
          },
          &RequestHeader::MergeImpl,
          &RequestHeader::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2fheader_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> RequestHeader::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RequestHeader_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::RequestHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .google.protobuf.Timestamp request_timestamp = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_.request_timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp request_timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_.request_timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void RequestHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.RequestHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.request_timestamp_ != nullptr);
    _impl_.request_timestamp_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RequestHeader::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.RequestHeader)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp request_timestamp = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.request_timestamp_, _impl_.request_timestamp_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.RequestHeader)
  return target;
}

::size_t RequestHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.RequestHeader)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Timestamp request_timestamp = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.request_timestamp_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RequestHeader::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestHeader*>(&to_msg);
  auto& from = static_cast<const RequestHeader&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.RequestHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.request_timestamp_ != nullptr);
    if (_this->_impl_.request_timestamp_ == nullptr) {
      _this->_impl_.request_timestamp_ =
          ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.request_timestamp_);
    } else {
      _this->_impl_.request_timestamp_->MergeFrom(*from._impl_.request_timestamp_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestHeader::CopyFrom(const RequestHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.RequestHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestHeader::InternalSwap(RequestHeader* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.request_timestamp_, other->_impl_.request_timestamp_);
}

::google::protobuf::Metadata RequestHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResponseHeader::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ResponseHeader>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_._has_bits_);
};

void ResponseHeader::clear_request_received_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_received_timestamp_ != nullptr) _impl_.request_received_timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void ResponseHeader::clear_response_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_timestamp_ != nullptr) _impl_.response_timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
ResponseHeader::ResponseHeader(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.ResponseHeader)
}
inline PROTOBUF_NDEBUG_INLINE ResponseHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::ResponseHeader& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ResponseHeader::ResponseHeader(
    ::google::protobuf::Arena* arena,
    const ResponseHeader& from)
    : ::google::protobuf::Message(arena) {
  ResponseHeader* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.request_header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::RequestHeader>(
                              arena, *from._impl_.request_header_)
                        : nullptr;
  _impl_.request_received_timestamp_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.request_received_timestamp_)
                        : nullptr;
  _impl_.response_timestamp_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.response_timestamp_)
                        : nullptr;
  _impl_.error_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::CommonError>(
                              arena, *from._impl_.error_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:rb.api.ResponseHeader)
}
inline PROTOBUF_NDEBUG_INLINE ResponseHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ResponseHeader::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, request_header_),
           0,
           offsetof(Impl_, error_) -
               offsetof(Impl_, request_header_) +
               sizeof(Impl_::error_));
}
ResponseHeader::~ResponseHeader() {
  // @@protoc_insertion_point(destructor:rb.api.ResponseHeader)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ResponseHeader::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.request_header_;
  delete _impl_.request_received_timestamp_;
  delete _impl_.response_timestamp_;
  delete _impl_.error_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ResponseHeader::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_._cached_size_),
              false,
          },
          &ResponseHeader::MergeImpl,
          &ResponseHeader::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2fheader_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 4, 0, 2> ResponseHeader::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ResponseHeader_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::ResponseHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .rb.api.CommonError error = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3, PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.error_)}},
    // .rb.api.RequestHeader request_header = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.request_header_)}},
    // .google.protobuf.Timestamp request_received_timestamp = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.request_received_timestamp_)}},
    // .google.protobuf.Timestamp response_timestamp = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.response_timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rb.api.RequestHeader request_header = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.request_header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp request_received_timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.request_received_timestamp_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp response_timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.response_timestamp_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.CommonError error = 4;
    {PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.error_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::rb::api::RequestHeader>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::rb::api::CommonError>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ResponseHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.ResponseHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.request_header_ != nullptr);
      _impl_.request_header_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.request_received_timestamp_ != nullptr);
      _impl_.request_received_timestamp_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.response_timestamp_ != nullptr);
      _impl_.response_timestamp_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.error_ != nullptr);
      _impl_.error_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ResponseHeader::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.ResponseHeader)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .rb.api.RequestHeader request_header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.request_header_, _impl_.request_header_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.Timestamp request_received_timestamp = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.request_received_timestamp_, _impl_.request_received_timestamp_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.Timestamp response_timestamp = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.response_timestamp_, _impl_.response_timestamp_->GetCachedSize(), target, stream);
  }

  // .rb.api.CommonError error = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *_impl_.error_, _impl_.error_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.ResponseHeader)
  return target;
}

::size_t ResponseHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.ResponseHeader)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // .rb.api.RequestHeader request_header = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.request_header_);
    }

    // .google.protobuf.Timestamp request_received_timestamp = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.request_received_timestamp_);
    }

    // .google.protobuf.Timestamp response_timestamp = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.response_timestamp_);
    }

    // .rb.api.CommonError error = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.error_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ResponseHeader::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResponseHeader*>(&to_msg);
  auto& from = static_cast<const ResponseHeader&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.ResponseHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.request_header_ != nullptr);
      if (_this->_impl_.request_header_ == nullptr) {
        _this->_impl_.request_header_ =
            ::google::protobuf::Message::CopyConstruct<::rb::api::RequestHeader>(arena, *from._impl_.request_header_);
      } else {
        _this->_impl_.request_header_->MergeFrom(*from._impl_.request_header_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.request_received_timestamp_ != nullptr);
      if (_this->_impl_.request_received_timestamp_ == nullptr) {
        _this->_impl_.request_received_timestamp_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.request_received_timestamp_);
      } else {
        _this->_impl_.request_received_timestamp_->MergeFrom(*from._impl_.request_received_timestamp_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.response_timestamp_ != nullptr);
      if (_this->_impl_.response_timestamp_ == nullptr) {
        _this->_impl_.response_timestamp_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.response_timestamp_);
      } else {
        _this->_impl_.response_timestamp_->MergeFrom(*from._impl_.response_timestamp_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.error_ != nullptr);
      if (_this->_impl_.error_ == nullptr) {
        _this->_impl_.error_ =
            ::google::protobuf::Message::CopyConstruct<::rb::api::CommonError>(arena, *from._impl_.error_);
      } else {
        _this->_impl_.error_->MergeFrom(*from._impl_.error_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResponseHeader::CopyFrom(const ResponseHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.ResponseHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResponseHeader::InternalSwap(ResponseHeader* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.error_)
      + sizeof(ResponseHeader::_impl_.error_)
      - PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.request_header_)>(
          reinterpret_cast<char*>(&_impl_.request_header_),
          reinterpret_cast<char*>(&other->_impl_.request_header_));
}

::google::protobuf::Metadata ResponseHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CommonError::_Internal {
 public:
};

CommonError::CommonError(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.CommonError)
}
inline PROTOBUF_NDEBUG_INLINE CommonError::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::CommonError& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

CommonError::CommonError(
    ::google::protobuf::Arena* arena,
    const CommonError& from)
    : ::google::protobuf::Message(arena) {
  CommonError* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:rb.api.CommonError)
}
inline PROTOBUF_NDEBUG_INLINE CommonError::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void CommonError::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.code_ = {};
}
CommonError::~CommonError() {
  // @@protoc_insertion_point(destructor:rb.api.CommonError)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CommonError::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CommonError::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CommonError, _impl_._cached_size_),
              false,
          },
          &CommonError::MergeImpl,
          &CommonError::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2fheader_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2> CommonError::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CommonError_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::CommonError>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CommonError, _impl_.message_)}},
    // .rb.api.CommonError.Code code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CommonError, _impl_.code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CommonError, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rb.api.CommonError.Code code = 1;
    {PROTOBUF_FIELD_OFFSET(CommonError, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(CommonError, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\7\0\0\0\0\0"
    "rb.api.CommonError"
    "message"
  }},
};

PROTOBUF_NOINLINE void CommonError::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.CommonError)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CommonError::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.CommonError)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .rb.api.CommonError.Code code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rb.api.CommonError.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.CommonError)
  return target;
}

::size_t CommonError::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.CommonError)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // .rb.api.CommonError.Code code = 1;
  if (this->_internal_code() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CommonError::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CommonError*>(&to_msg);
  auto& from = static_cast<const CommonError&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.CommonError)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_impl_.code_ = from._impl_.code_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommonError::CopyFrom(const CommonError& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.CommonError)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CommonError::InternalSwap(CommonError* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.code_, other->_impl_.code_);
}

::google::protobuf::Metadata CommonError::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace rb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rb_2fapi_2fheader_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
