// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rb/api/led.proto
// Protobuf C++ Version: 5.27.0

#include "rb/api/led.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rb {
namespace api {

inline constexpr SetLEDColorRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        request_header_{nullptr},
        color_{nullptr},
        duration_{nullptr},
        transition_time_{nullptr},
        blinking_freq_{nullptr},
        blinking_{false} {}

template <typename>
PROTOBUF_CONSTEXPR SetLEDColorRequest::SetLEDColorRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SetLEDColorRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetLEDColorRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetLEDColorRequestDefaultTypeInternal() {}
  union {
    SetLEDColorRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetLEDColorRequestDefaultTypeInternal _SetLEDColorRequest_default_instance_;

inline constexpr SetLEDColorResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        response_header_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR SetLEDColorResponse::SetLEDColorResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SetLEDColorResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetLEDColorResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetLEDColorResponseDefaultTypeInternal() {}
  union {
    SetLEDColorResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetLEDColorResponseDefaultTypeInternal _SetLEDColorResponse_default_instance_;
}  // namespace api
}  // namespace rb
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_rb_2fapi_2fled_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rb_2fapi_2fled_2eproto = nullptr;
const ::uint32_t
    TableStruct_rb_2fapi_2fled_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorRequest, _impl_.request_header_),
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorRequest, _impl_.color_),
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorRequest, _impl_.duration_),
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorRequest, _impl_.transition_time_),
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorRequest, _impl_.blinking_),
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorRequest, _impl_.blinking_freq_),
        0,
        1,
        2,
        3,
        ~0u,
        4,
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::SetLEDColorResponse, _impl_.response_header_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::rb::api::SetLEDColorRequest)},
        {20, 29, -1, sizeof(::rb::api::SetLEDColorResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::rb::api::_SetLEDColorRequest_default_instance_._instance,
    &::rb::api::_SetLEDColorResponse_default_instance_._instance,
};
const char descriptor_table_protodef_rb_2fapi_2fled_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020rb/api/led.proto\022\006rb.api\032\022rb/api/color"
    ".proto\032\023rb/api/header.proto\032\036google/prot"
    "obuf/duration.proto\032\036google/protobuf/wra"
    "ppers.proto\"\211\002\n\022SetLEDColorRequest\022-\n\016re"
    "quest_header\030\001 \001(\0132\025.rb.api.RequestHeade"
    "r\022\034\n\005color\030\002 \001(\0132\r.rb.api.Color\022+\n\010durat"
    "ion\030\003 \001(\0132\031.google.protobuf.Duration\0222\n\017"
    "transition_time\030\004 \001(\0132\031.google.protobuf."
    "Duration\022\020\n\010blinking\030\005 \001(\010\0223\n\rblinking_f"
    "req\030\006 \001(\0132\034.google.protobuf.DoubleValue\""
    "F\n\023SetLEDColorResponse\022/\n\017response_heade"
    "r\030\001 \001(\0132\026.rb.api.ResponseHeaderb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_rb_2fapi_2fled_2eproto_deps[4] =
    {
        &::descriptor_table_google_2fprotobuf_2fduration_2eproto,
        &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
        &::descriptor_table_rb_2fapi_2fcolor_2eproto,
        &::descriptor_table_rb_2fapi_2fheader_2eproto,
};
static ::absl::once_flag descriptor_table_rb_2fapi_2fled_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rb_2fapi_2fled_2eproto = {
    false,
    false,
    479,
    descriptor_table_protodef_rb_2fapi_2fled_2eproto,
    "rb/api/led.proto",
    &descriptor_table_rb_2fapi_2fled_2eproto_once,
    descriptor_table_rb_2fapi_2fled_2eproto_deps,
    4,
    2,
    schemas,
    file_default_instances,
    TableStruct_rb_2fapi_2fled_2eproto::offsets,
    file_level_enum_descriptors_rb_2fapi_2fled_2eproto,
    file_level_service_descriptors_rb_2fapi_2fled_2eproto,
};
namespace rb {
namespace api {
// ===================================================================

class SetLEDColorRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SetLEDColorRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_._has_bits_);
};

void SetLEDColorRequest::clear_request_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_header_ != nullptr) _impl_.request_header_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void SetLEDColorRequest::clear_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.color_ != nullptr) _impl_.color_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void SetLEDColorRequest::clear_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.duration_ != nullptr) _impl_.duration_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void SetLEDColorRequest::clear_transition_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.transition_time_ != nullptr) _impl_.transition_time_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
void SetLEDColorRequest::clear_blinking_freq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.blinking_freq_ != nullptr) _impl_.blinking_freq_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
SetLEDColorRequest::SetLEDColorRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.SetLEDColorRequest)
}
inline PROTOBUF_NDEBUG_INLINE SetLEDColorRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::SetLEDColorRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SetLEDColorRequest::SetLEDColorRequest(
    ::google::protobuf::Arena* arena,
    const SetLEDColorRequest& from)
    : ::google::protobuf::Message(arena) {
  SetLEDColorRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.request_header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::RequestHeader>(
                              arena, *from._impl_.request_header_)
                        : nullptr;
  _impl_.color_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::Color>(
                              arena, *from._impl_.color_)
                        : nullptr;
  _impl_.duration_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(
                              arena, *from._impl_.duration_)
                        : nullptr;
  _impl_.transition_time_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(
                              arena, *from._impl_.transition_time_)
                        : nullptr;
  _impl_.blinking_freq_ = (cached_has_bits & 0x00000010u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::DoubleValue>(
                              arena, *from._impl_.blinking_freq_)
                        : nullptr;
  _impl_.blinking_ = from._impl_.blinking_;

  // @@protoc_insertion_point(copy_constructor:rb.api.SetLEDColorRequest)
}
inline PROTOBUF_NDEBUG_INLINE SetLEDColorRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SetLEDColorRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, request_header_),
           0,
           offsetof(Impl_, blinking_) -
               offsetof(Impl_, request_header_) +
               sizeof(Impl_::blinking_));
}
SetLEDColorRequest::~SetLEDColorRequest() {
  // @@protoc_insertion_point(destructor:rb.api.SetLEDColorRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SetLEDColorRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.request_header_;
  delete _impl_.color_;
  delete _impl_.duration_;
  delete _impl_.transition_time_;
  delete _impl_.blinking_freq_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SetLEDColorRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_._cached_size_),
              false,
          },
          &SetLEDColorRequest::MergeImpl,
          &SetLEDColorRequest::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2fled_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 5, 0, 2> SetLEDColorRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_SetLEDColorRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::SetLEDColorRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .rb.api.RequestHeader request_header = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.request_header_)}},
    // .rb.api.Color color = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.color_)}},
    // .google.protobuf.Duration duration = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.duration_)}},
    // .google.protobuf.Duration transition_time = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3, PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.transition_time_)}},
    // bool blinking = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SetLEDColorRequest, _impl_.blinking_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.blinking_)}},
    // .google.protobuf.DoubleValue blinking_freq = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 4, 4, PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.blinking_freq_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .rb.api.RequestHeader request_header = 1;
    {PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.request_header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.Color color = 2;
    {PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.color_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Duration duration = 3;
    {PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.duration_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Duration transition_time = 4;
    {PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.transition_time_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool blinking = 5;
    {PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.blinking_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // .google.protobuf.DoubleValue blinking_freq = 6;
    {PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.blinking_freq_), _Internal::kHasBitsOffset + 4, 4,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::rb::api::RequestHeader>()},
    {::_pbi::TcParser::GetTable<::rb::api::Color>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Duration>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Duration>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::DoubleValue>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SetLEDColorRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.SetLEDColorRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.request_header_ != nullptr);
      _impl_.request_header_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.color_ != nullptr);
      _impl_.color_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.duration_ != nullptr);
      _impl_.duration_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.transition_time_ != nullptr);
      _impl_.transition_time_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(_impl_.blinking_freq_ != nullptr);
      _impl_.blinking_freq_->Clear();
    }
  }
  _impl_.blinking_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SetLEDColorRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.SetLEDColorRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .rb.api.RequestHeader request_header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.request_header_, _impl_.request_header_->GetCachedSize(), target, stream);
  }

  // .rb.api.Color color = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.color_, _impl_.color_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.Duration duration = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.duration_, _impl_.duration_->GetCachedSize(), target, stream);
  }

  // .google.protobuf.Duration transition_time = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *_impl_.transition_time_, _impl_.transition_time_->GetCachedSize(), target, stream);
  }

  // bool blinking = 5;
  if (this->_internal_blinking() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        5, this->_internal_blinking(), target);
  }

  // .google.protobuf.DoubleValue blinking_freq = 6;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *_impl_.blinking_freq_, _impl_.blinking_freq_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.SetLEDColorRequest)
  return target;
}

::size_t SetLEDColorRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.SetLEDColorRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // .rb.api.RequestHeader request_header = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.request_header_);
    }

    // .rb.api.Color color = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.color_);
    }

    // .google.protobuf.Duration duration = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.duration_);
    }

    // .google.protobuf.Duration transition_time = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.transition_time_);
    }

    // .google.protobuf.DoubleValue blinking_freq = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.blinking_freq_);
    }

  }
  // bool blinking = 5;
  if (this->_internal_blinking() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SetLEDColorRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SetLEDColorRequest*>(&to_msg);
  auto& from = static_cast<const SetLEDColorRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.SetLEDColorRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.request_header_ != nullptr);
      if (_this->_impl_.request_header_ == nullptr) {
        _this->_impl_.request_header_ =
            ::google::protobuf::Message::CopyConstruct<::rb::api::RequestHeader>(arena, *from._impl_.request_header_);
      } else {
        _this->_impl_.request_header_->MergeFrom(*from._impl_.request_header_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.color_ != nullptr);
      if (_this->_impl_.color_ == nullptr) {
        _this->_impl_.color_ =
            ::google::protobuf::Message::CopyConstruct<::rb::api::Color>(arena, *from._impl_.color_);
      } else {
        _this->_impl_.color_->MergeFrom(*from._impl_.color_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.duration_ != nullptr);
      if (_this->_impl_.duration_ == nullptr) {
        _this->_impl_.duration_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(arena, *from._impl_.duration_);
      } else {
        _this->_impl_.duration_->MergeFrom(*from._impl_.duration_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.transition_time_ != nullptr);
      if (_this->_impl_.transition_time_ == nullptr) {
        _this->_impl_.transition_time_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(arena, *from._impl_.transition_time_);
      } else {
        _this->_impl_.transition_time_->MergeFrom(*from._impl_.transition_time_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(from._impl_.blinking_freq_ != nullptr);
      if (_this->_impl_.blinking_freq_ == nullptr) {
        _this->_impl_.blinking_freq_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::DoubleValue>(arena, *from._impl_.blinking_freq_);
      } else {
        _this->_impl_.blinking_freq_->MergeFrom(*from._impl_.blinking_freq_);
      }
    }
  }
  if (from._internal_blinking() != 0) {
    _this->_impl_.blinking_ = from._impl_.blinking_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SetLEDColorRequest::CopyFrom(const SetLEDColorRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.SetLEDColorRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SetLEDColorRequest::InternalSwap(SetLEDColorRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.blinking_)
      + sizeof(SetLEDColorRequest::_impl_.blinking_)
      - PROTOBUF_FIELD_OFFSET(SetLEDColorRequest, _impl_.request_header_)>(
          reinterpret_cast<char*>(&_impl_.request_header_),
          reinterpret_cast<char*>(&other->_impl_.request_header_));
}

::google::protobuf::Metadata SetLEDColorRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SetLEDColorResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SetLEDColorResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SetLEDColorResponse, _impl_._has_bits_);
};

void SetLEDColorResponse::clear_response_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_header_ != nullptr) _impl_.response_header_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
SetLEDColorResponse::SetLEDColorResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.SetLEDColorResponse)
}
inline PROTOBUF_NDEBUG_INLINE SetLEDColorResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::SetLEDColorResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SetLEDColorResponse::SetLEDColorResponse(
    ::google::protobuf::Arena* arena,
    const SetLEDColorResponse& from)
    : ::google::protobuf::Message(arena) {
  SetLEDColorResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.response_header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::ResponseHeader>(
                              arena, *from._impl_.response_header_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:rb.api.SetLEDColorResponse)
}
inline PROTOBUF_NDEBUG_INLINE SetLEDColorResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SetLEDColorResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.response_header_ = {};
}
SetLEDColorResponse::~SetLEDColorResponse() {
  // @@protoc_insertion_point(destructor:rb.api.SetLEDColorResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SetLEDColorResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.response_header_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SetLEDColorResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SetLEDColorResponse, _impl_._cached_size_),
              false,
          },
          &SetLEDColorResponse::MergeImpl,
          &SetLEDColorResponse::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2fled_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> SetLEDColorResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SetLEDColorResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_SetLEDColorResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::SetLEDColorResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .rb.api.ResponseHeader response_header = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SetLEDColorResponse, _impl_.response_header_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rb.api.ResponseHeader response_header = 1;
    {PROTOBUF_FIELD_OFFSET(SetLEDColorResponse, _impl_.response_header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::rb::api::ResponseHeader>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SetLEDColorResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.SetLEDColorResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.response_header_ != nullptr);
    _impl_.response_header_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SetLEDColorResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.SetLEDColorResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .rb.api.ResponseHeader response_header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.response_header_, _impl_.response_header_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.SetLEDColorResponse)
  return target;
}

::size_t SetLEDColorResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.SetLEDColorResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .rb.api.ResponseHeader response_header = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.response_header_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SetLEDColorResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SetLEDColorResponse*>(&to_msg);
  auto& from = static_cast<const SetLEDColorResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.SetLEDColorResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.response_header_ != nullptr);
    if (_this->_impl_.response_header_ == nullptr) {
      _this->_impl_.response_header_ =
          ::google::protobuf::Message::CopyConstruct<::rb::api::ResponseHeader>(arena, *from._impl_.response_header_);
    } else {
      _this->_impl_.response_header_->MergeFrom(*from._impl_.response_header_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SetLEDColorResponse::CopyFrom(const SetLEDColorResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.SetLEDColorResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SetLEDColorResponse::InternalSwap(SetLEDColorResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.response_header_, other->_impl_.response_header_);
}

::google::protobuf::Metadata SetLEDColorResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace rb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rb_2fapi_2fled_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
