// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rb/api/led_service.proto

#include "rb/api/led_service.pb.h"
#include "rb/api/led_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rb {
namespace api {

static const char* LEDService_method_names[] = {
  "/rb.api.LEDService/SetLEDColor",
};

std::unique_ptr< LEDService::Stub> LEDService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LEDService::Stub> stub(new LEDService::Stub(channel, options));
  return stub;
}

LEDService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetLEDColor_(LEDService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LEDService::Stub::SetLEDColor(::grpc::ClientContext* context, const ::rb::api::SetLEDColorRequest& request, ::rb::api::SetLEDColorResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rb::api::SetLEDColorRequest, ::rb::api::SetLEDColorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetLEDColor_, context, request, response);
}

void LEDService::Stub::async::SetLEDColor(::grpc::ClientContext* context, const ::rb::api::SetLEDColorRequest* request, ::rb::api::SetLEDColorResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rb::api::SetLEDColorRequest, ::rb::api::SetLEDColorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetLEDColor_, context, request, response, std::move(f));
}

void LEDService::Stub::async::SetLEDColor(::grpc::ClientContext* context, const ::rb::api::SetLEDColorRequest* request, ::rb::api::SetLEDColorResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetLEDColor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rb::api::SetLEDColorResponse>* LEDService::Stub::PrepareAsyncSetLEDColorRaw(::grpc::ClientContext* context, const ::rb::api::SetLEDColorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rb::api::SetLEDColorResponse, ::rb::api::SetLEDColorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetLEDColor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rb::api::SetLEDColorResponse>* LEDService::Stub::AsyncSetLEDColorRaw(::grpc::ClientContext* context, const ::rb::api::SetLEDColorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetLEDColorRaw(context, request, cq);
  result->StartCall();
  return result;
}

LEDService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LEDService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LEDService::Service, ::rb::api::SetLEDColorRequest, ::rb::api::SetLEDColorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LEDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rb::api::SetLEDColorRequest* req,
             ::rb::api::SetLEDColorResponse* resp) {
               return service->SetLEDColor(ctx, req, resp);
             }, this)));
}

LEDService::Service::~Service() {
}

::grpc::Status LEDService::Service::SetLEDColor(::grpc::ServerContext* context, const ::rb::api::SetLEDColorRequest* request, ::rb::api::SetLEDColorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rb
}  // namespace api

