// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rb/api/robot_info_service.proto
#ifndef GRPC_rb_2fapi_2frobot_5finfo_5fservice_2eproto__INCLUDED
#define GRPC_rb_2fapi_2frobot_5finfo_5fservice_2eproto__INCLUDED

#include "rb/api/robot_info_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace rb {
namespace api {

class RobotInfoService final {
 public:
  static constexpr char const* service_full_name() {
    return "rb.api.RobotInfoService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::rb::api::GetRobotInfoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotInfoResponse>> AsyncGetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotInfoResponse>>(AsyncGetRobotInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotInfoResponse>> PrepareAsyncGetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotInfoResponse>>(PrepareAsyncGetRobotInfoRaw(context, request, cq));
    }
    virtual ::grpc::Status GetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::rb::api::GetRobotModelResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotModelResponse>> AsyncGetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotModelResponse>>(AsyncGetRobotModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotModelResponse>> PrepareAsyncGetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotModelResponse>>(PrepareAsyncGetRobotModelRaw(context, request, cq));
    }
    virtual ::grpc::Status ImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::rb::api::ImportRobotModelResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ImportRobotModelResponse>> AsyncImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ImportRobotModelResponse>>(AsyncImportRobotModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ImportRobotModelResponse>> PrepareAsyncImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ImportRobotModelResponse>>(PrepareAsyncImportRobotModelRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest* request, ::rb::api::GetRobotInfoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest* request, ::rb::api::GetRobotInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest* request, ::rb::api::GetRobotModelResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest* request, ::rb::api::GetRobotModelResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest* request, ::rb::api::ImportRobotModelResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest* request, ::rb::api::ImportRobotModelResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotInfoResponse>* AsyncGetRobotInfoRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotInfoResponse>* PrepareAsyncGetRobotInfoRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotModelResponse>* AsyncGetRobotModelRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotModelResponse>* PrepareAsyncGetRobotModelRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ImportRobotModelResponse>* AsyncImportRobotModelRaw(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ImportRobotModelResponse>* PrepareAsyncImportRobotModelRaw(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::rb::api::GetRobotInfoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotInfoResponse>> AsyncGetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotInfoResponse>>(AsyncGetRobotInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotInfoResponse>> PrepareAsyncGetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotInfoResponse>>(PrepareAsyncGetRobotInfoRaw(context, request, cq));
    }
    ::grpc::Status GetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::rb::api::GetRobotModelResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotModelResponse>> AsyncGetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotModelResponse>>(AsyncGetRobotModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotModelResponse>> PrepareAsyncGetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotModelResponse>>(PrepareAsyncGetRobotModelRaw(context, request, cq));
    }
    ::grpc::Status ImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::rb::api::ImportRobotModelResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ImportRobotModelResponse>> AsyncImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ImportRobotModelResponse>>(AsyncImportRobotModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ImportRobotModelResponse>> PrepareAsyncImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ImportRobotModelResponse>>(PrepareAsyncImportRobotModelRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest* request, ::rb::api::GetRobotInfoResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRobotInfo(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest* request, ::rb::api::GetRobotInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest* request, ::rb::api::GetRobotModelResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRobotModel(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest* request, ::rb::api::GetRobotModelResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest* request, ::rb::api::ImportRobotModelResponse* response, std::function<void(::grpc::Status)>) override;
      void ImportRobotModel(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest* request, ::rb::api::ImportRobotModelResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotInfoResponse>* AsyncGetRobotInfoRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotInfoResponse>* PrepareAsyncGetRobotInfoRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotModelResponse>* AsyncGetRobotModelRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotModelResponse>* PrepareAsyncGetRobotModelRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotModelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::ImportRobotModelResponse>* AsyncImportRobotModelRaw(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::ImportRobotModelResponse>* PrepareAsyncImportRobotModelRaw(::grpc::ClientContext* context, const ::rb::api::ImportRobotModelRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetRobotInfo_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRobotModel_;
    const ::grpc::internal::RpcMethod rpcmethod_ImportRobotModel_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetRobotInfo(::grpc::ServerContext* context, const ::rb::api::GetRobotInfoRequest* request, ::rb::api::GetRobotInfoResponse* response);
    virtual ::grpc::Status GetRobotModel(::grpc::ServerContext* context, const ::rb::api::GetRobotModelRequest* request, ::rb::api::GetRobotModelResponse* response);
    virtual ::grpc::Status ImportRobotModel(::grpc::ServerContext* context, const ::rb::api::ImportRobotModelRequest* request, ::rb::api::ImportRobotModelResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRobotInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRobotInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetRobotInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotInfo(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotInfoRequest* /*request*/, ::rb::api::GetRobotInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotInfo(::grpc::ServerContext* context, ::rb::api::GetRobotInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::GetRobotInfoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRobotModel() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotModelRequest* /*request*/, ::rb::api::GetRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotModel(::grpc::ServerContext* context, ::rb::api::GetRobotModelRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::GetRobotModelResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ImportRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ImportRobotModel() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ImportRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImportRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::ImportRobotModelRequest* /*request*/, ::rb::api::ImportRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestImportRobotModel(::grpc::ServerContext* context, ::rb::api::ImportRobotModelRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::ImportRobotModelResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetRobotInfo<WithAsyncMethod_GetRobotModel<WithAsyncMethod_ImportRobotModel<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetRobotInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRobotInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::GetRobotInfoRequest, ::rb::api::GetRobotInfoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::GetRobotInfoRequest* request, ::rb::api::GetRobotInfoResponse* response) { return this->GetRobotInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetRobotInfo(
        ::grpc::MessageAllocator< ::rb::api::GetRobotInfoRequest, ::rb::api::GetRobotInfoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::GetRobotInfoRequest, ::rb::api::GetRobotInfoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRobotInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotInfo(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotInfoRequest* /*request*/, ::rb::api::GetRobotInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRobotInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::GetRobotInfoRequest* /*request*/, ::rb::api::GetRobotInfoResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRobotModel() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::GetRobotModelRequest, ::rb::api::GetRobotModelResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::GetRobotModelRequest* request, ::rb::api::GetRobotModelResponse* response) { return this->GetRobotModel(context, request, response); }));}
    void SetMessageAllocatorFor_GetRobotModel(
        ::grpc::MessageAllocator< ::rb::api::GetRobotModelRequest, ::rb::api::GetRobotModelResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::GetRobotModelRequest, ::rb::api::GetRobotModelResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotModelRequest* /*request*/, ::rb::api::GetRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRobotModel(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::GetRobotModelRequest* /*request*/, ::rb::api::GetRobotModelResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ImportRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ImportRobotModel() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::ImportRobotModelRequest, ::rb::api::ImportRobotModelResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::ImportRobotModelRequest* request, ::rb::api::ImportRobotModelResponse* response) { return this->ImportRobotModel(context, request, response); }));}
    void SetMessageAllocatorFor_ImportRobotModel(
        ::grpc::MessageAllocator< ::rb::api::ImportRobotModelRequest, ::rb::api::ImportRobotModelResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::ImportRobotModelRequest, ::rb::api::ImportRobotModelResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ImportRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImportRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::ImportRobotModelRequest* /*request*/, ::rb::api::ImportRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ImportRobotModel(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::ImportRobotModelRequest* /*request*/, ::rb::api::ImportRobotModelResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetRobotInfo<WithCallbackMethod_GetRobotModel<WithCallbackMethod_ImportRobotModel<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetRobotInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRobotInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetRobotInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotInfo(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotInfoRequest* /*request*/, ::rb::api::GetRobotInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRobotModel() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotModelRequest* /*request*/, ::rb::api::GetRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ImportRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ImportRobotModel() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ImportRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImportRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::ImportRobotModelRequest* /*request*/, ::rb::api::ImportRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRobotInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRobotInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetRobotInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotInfo(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotInfoRequest* /*request*/, ::rb::api::GetRobotInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRobotModel() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotModelRequest* /*request*/, ::rb::api::GetRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotModel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ImportRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ImportRobotModel() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ImportRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImportRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::ImportRobotModelRequest* /*request*/, ::rb::api::ImportRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestImportRobotModel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRobotInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRobotInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRobotInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRobotInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotInfo(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotInfoRequest* /*request*/, ::rb::api::GetRobotInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRobotInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRobotModel() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRobotModel(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotModelRequest* /*request*/, ::rb::api::GetRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRobotModel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ImportRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ImportRobotModel() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ImportRobotModel(context, request, response); }));
    }
    ~WithRawCallbackMethod_ImportRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ImportRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::ImportRobotModelRequest* /*request*/, ::rb::api::ImportRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ImportRobotModel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRobotInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRobotInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::GetRobotInfoRequest, ::rb::api::GetRobotInfoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::GetRobotInfoRequest, ::rb::api::GetRobotInfoResponse>* streamer) {
                       return this->StreamedGetRobotInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRobotInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRobotInfo(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotInfoRequest* /*request*/, ::rb::api::GetRobotInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRobotInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::GetRobotInfoRequest,::rb::api::GetRobotInfoResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRobotModel() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::GetRobotModelRequest, ::rb::api::GetRobotModelResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::GetRobotModelRequest, ::rb::api::GetRobotModelResponse>* streamer) {
                       return this->StreamedGetRobotModel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotModelRequest* /*request*/, ::rb::api::GetRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRobotModel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::GetRobotModelRequest,::rb::api::GetRobotModelResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ImportRobotModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ImportRobotModel() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::ImportRobotModelRequest, ::rb::api::ImportRobotModelResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::ImportRobotModelRequest, ::rb::api::ImportRobotModelResponse>* streamer) {
                       return this->StreamedImportRobotModel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ImportRobotModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ImportRobotModel(::grpc::ServerContext* /*context*/, const ::rb::api::ImportRobotModelRequest* /*request*/, ::rb::api::ImportRobotModelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedImportRobotModel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::ImportRobotModelRequest,::rb::api::ImportRobotModelResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetRobotInfo<WithStreamedUnaryMethod_GetRobotModel<WithStreamedUnaryMethod_ImportRobotModel<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetRobotInfo<WithStreamedUnaryMethod_GetRobotModel<WithStreamedUnaryMethod_ImportRobotModel<Service > > > StreamedService;
};

}  // namespace api
}  // namespace rb


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_rb_2fapi_2frobot_5finfo_5fservice_2eproto__INCLUDED
