// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rb/api/robot_command.proto
// Protobuf C++ Version: 5.27.0

#include "rb/api/robot_command.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rb {
namespace api {
      template <typename>
PROTOBUF_CONSTEXPR RobotCommand::RobotCommand(::_pbi::ConstantInitialized) {}
struct RobotCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotCommandDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotCommandDefaultTypeInternal() {}
  union {
    RobotCommand _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotCommandDefaultTypeInternal _RobotCommand_default_instance_;

inline constexpr RobotCommand_Feedback::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        command_header_feedback_{nullptr},
        status_{static_cast< ::rb::api::RobotCommand_Feedback_Status >(0)},
        finish_code_{static_cast< ::rb::api::RobotCommand_Feedback_FinishCode >(0)},
        feedback_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR RobotCommand_Feedback::RobotCommand_Feedback(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RobotCommand_FeedbackDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotCommand_FeedbackDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotCommand_FeedbackDefaultTypeInternal() {}
  union {
    RobotCommand_Feedback _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotCommand_FeedbackDefaultTypeInternal _RobotCommand_Feedback_default_instance_;

inline constexpr RobotCommandResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        response_header_{nullptr},
        feedback_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR RobotCommandResponse::RobotCommandResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RobotCommandResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotCommandResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotCommandResponseDefaultTypeInternal() {}
  union {
    RobotCommandResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotCommandResponseDefaultTypeInternal _RobotCommandResponse_default_instance_;

inline constexpr RobotCommand_Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        command_header_{nullptr},
        command_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR RobotCommand_Request::RobotCommand_Request(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RobotCommand_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotCommand_RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotCommand_RequestDefaultTypeInternal() {}
  union {
    RobotCommand_Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotCommand_RequestDefaultTypeInternal _RobotCommand_Request_default_instance_;

inline constexpr RobotCommandRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        request_header_{nullptr},
        robot_command_{nullptr},
        priority_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RobotCommandRequest::RobotCommandRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RobotCommandRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotCommandRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotCommandRequestDefaultTypeInternal() {}
  union {
    RobotCommandRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotCommandRequestDefaultTypeInternal _RobotCommandRequest_default_instance_;
}  // namespace api
}  // namespace rb
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_rb_2fapi_2frobot_5fcommand_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rb_2fapi_2frobot_5fcommand_2eproto = nullptr;
const ::uint32_t
    TableStruct_rb_2fapi_2frobot_5fcommand_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Request, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Request, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Request, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Request, _impl_.command_header_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Request, _impl_.command_),
        0,
        ~0u,
        ~0u,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Feedback, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Feedback, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Feedback, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Feedback, _impl_.command_header_feedback_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Feedback, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Feedback, _impl_.finish_code_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Feedback, _impl_.feedback_),
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandRequest, _impl_.request_header_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandRequest, _impl_.robot_command_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandRequest, _impl_.priority_),
        0,
        1,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandResponse, _impl_.response_header_),
        PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommandResponse, _impl_.feedback_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 13, -1, sizeof(::rb::api::RobotCommand_Request)},
        {17, 32, -1, sizeof(::rb::api::RobotCommand_Feedback)},
        {38, -1, -1, sizeof(::rb::api::RobotCommand)},
        {46, 57, -1, sizeof(::rb::api::RobotCommandRequest)},
        {60, 70, -1, sizeof(::rb::api::RobotCommandResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::rb::api::_RobotCommand_Request_default_instance_._instance,
    &::rb::api::_RobotCommand_Feedback_default_instance_._instance,
    &::rb::api::_RobotCommand_default_instance_._instance,
    &::rb::api::_RobotCommandRequest_default_instance_._instance,
    &::rb::api::_RobotCommandResponse_default_instance_._instance,
};
const char descriptor_table_protodef_rb_2fapi_2frobot_5fcommand_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032rb/api/robot_command.proto\022\006rb.api\032\023rb"
    "/api/header.proto\032\032rb/api/basic_command."
    "proto\032\033rb/api/command_header.proto\032\037rb/a"
    "pi/whole_body_command.proto\032$rb/api/comp"
    "onent_based_command.proto\"\244\010\n\014RobotComma"
    "nd\032\210\002\n\007Request\0225\n\016command_header\030\001 \001(\0132\035"
    ".rb.api.CommandHeader.Request\022>\n\022whole_b"
    "ody_command\030\002 \001(\0132 .rb.api.WholeBodyComm"
    "and.RequestH\000\022H\n\027component_based_command"
    "\030\003 \001(\0132%.rb.api.ComponentBasedCommand.Re"
    "questH\000\0221\n\013jog_command\030\004 \001(\0132\032.rb.api.Jo"
    "gCommand.RequestH\000B\t\n\007command\032\210\006\n\010Feedba"
    "ck\022\?\n\027command_header_feedback\030\001 \001(\0132\036.rb"
    ".api.CommandHeader.Feedback\022H\n\033whole_bod"
    "y_command_feedback\030\002 \001(\0132!.rb.api.WholeB"
    "odyCommand.FeedbackH\000\022R\n component_based"
    "_command_feedback\030\003 \001(\0132&.rb.api.Compone"
    "ntBasedCommand.FeedbackH\000\022;\n\024jog_command"
    "_feedback\030\004 \001(\0132\033.rb.api.JogCommand.Feed"
    "backH\000\0224\n\006status\030\n \001(\0162$.rb.api.RobotCom"
    "mand.Feedback.Status\022=\n\013finish_code\030\013 \001("
    "\0162(.rb.api.RobotCommand.Feedback.FinishC"
    "ode\"[\n\006Status\022\017\n\013STATUS_IDLE\020\000\022\027\n\023STATUS"
    "_INITIALIZING\020\001\022\022\n\016STATUS_RUNNING\020\002\022\023\n\017S"
    "TATUS_FINISHED\020\003\"\201\002\n\nFinishCode\022\027\n\023FINIS"
    "H_CODE_UNKNOWN\020\000\022\022\n\016FINISH_CODE_OK\020\001\022\030\n\024"
    "FINISH_CODE_CANCELED\020\002\022\031\n\025FINISH_CODE_PR"
    "EEMPTED\020\003\022\"\n\036FINISH_CODE_INITIALIZED_FAI"
    "LED\020\004\022$\n FINISH_CODE_CONTROL_MANAGER_IDL"
    "E\020\005\022%\n!FINISH_CODE_CONTROL_MANAGER_FAULT"
    "\020\006\022 \n\034FINISH_CODE_UNEXPECTED_STATE\020\007B\n\n\010"
    "feedback\"\213\001\n\023RobotCommandRequest\022-\n\016requ"
    "est_header\030\001 \001(\0132\025.rb.api.RequestHeader\022"
    "3\n\rrobot_command\030\002 \001(\0132\034.rb.api.RobotCom"
    "mand.Request\022\020\n\010priority\030\003 \001(\005\"x\n\024RobotC"
    "ommandResponse\022/\n\017response_header\030\001 \001(\0132"
    "\026.rb.api.ResponseHeader\022/\n\010feedback\030\002 \001("
    "\0132\035.rb.api.RobotCommand.Feedbackb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto_deps[5] =
    {
        &::descriptor_table_rb_2fapi_2fbasic_5fcommand_2eproto,
        &::descriptor_table_rb_2fapi_2fcommand_5fheader_2eproto,
        &::descriptor_table_rb_2fapi_2fcomponent_5fbased_5fcommand_2eproto,
        &::descriptor_table_rb_2fapi_2fheader_2eproto,
        &::descriptor_table_rb_2fapi_2fwhole_5fbody_5fcommand_2eproto,
};
static ::absl::once_flag descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto = {
    false,
    false,
    1520,
    descriptor_table_protodef_rb_2fapi_2frobot_5fcommand_2eproto,
    "rb/api/robot_command.proto",
    &descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto_once,
    descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto_deps,
    5,
    5,
    schemas,
    file_default_instances,
    TableStruct_rb_2fapi_2frobot_5fcommand_2eproto::offsets,
    file_level_enum_descriptors_rb_2fapi_2frobot_5fcommand_2eproto,
    file_level_service_descriptors_rb_2fapi_2frobot_5fcommand_2eproto,
};
namespace rb {
namespace api {
const ::google::protobuf::EnumDescriptor* RobotCommand_Feedback_Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto);
  return file_level_enum_descriptors_rb_2fapi_2frobot_5fcommand_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RobotCommand_Feedback_Status_internal_data_[] = {
    262144u, 0u, };
bool RobotCommand_Feedback_Status_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr RobotCommand_Feedback_Status RobotCommand_Feedback::STATUS_IDLE;
constexpr RobotCommand_Feedback_Status RobotCommand_Feedback::STATUS_INITIALIZING;
constexpr RobotCommand_Feedback_Status RobotCommand_Feedback::STATUS_RUNNING;
constexpr RobotCommand_Feedback_Status RobotCommand_Feedback::STATUS_FINISHED;
constexpr RobotCommand_Feedback_Status RobotCommand_Feedback::Status_MIN;
constexpr RobotCommand_Feedback_Status RobotCommand_Feedback::Status_MAX;
constexpr int RobotCommand_Feedback::Status_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* RobotCommand_Feedback_FinishCode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto);
  return file_level_enum_descriptors_rb_2fapi_2frobot_5fcommand_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t RobotCommand_Feedback_FinishCode_internal_data_[] = {
    524288u, 0u, };
bool RobotCommand_Feedback_FinishCode_IsValid(int value) {
  return 0 <= value && value <= 7;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FINISH_CODE_UNKNOWN;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FINISH_CODE_OK;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FINISH_CODE_CANCELED;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FINISH_CODE_PREEMPTED;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FINISH_CODE_INITIALIZED_FAILED;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FINISH_CODE_CONTROL_MANAGER_IDLE;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FINISH_CODE_CONTROL_MANAGER_FAULT;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FINISH_CODE_UNEXPECTED_STATE;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FinishCode_MIN;
constexpr RobotCommand_Feedback_FinishCode RobotCommand_Feedback::FinishCode_MAX;
constexpr int RobotCommand_Feedback::FinishCode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class RobotCommand_Request::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RobotCommand_Request>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RobotCommand_Request, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Request, _impl_._oneof_case_);
};

void RobotCommand_Request::clear_command_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.command_header_ != nullptr) _impl_.command_header_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void RobotCommand_Request::set_allocated_whole_body_command(::rb::api::WholeBodyCommand_Request* whole_body_command) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_command();
  if (whole_body_command) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(whole_body_command)->GetArena();
    if (message_arena != submessage_arena) {
      whole_body_command = ::google::protobuf::internal::GetOwnedMessage(message_arena, whole_body_command, submessage_arena);
    }
    set_has_whole_body_command();
    _impl_.command_.whole_body_command_ = whole_body_command;
  }
  // @@protoc_insertion_point(field_set_allocated:rb.api.RobotCommand.Request.whole_body_command)
}
void RobotCommand_Request::clear_whole_body_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (command_case() == kWholeBodyCommand) {
    if (GetArena() == nullptr) {
      delete _impl_.command_.whole_body_command_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.command_.whole_body_command_);
    }
    clear_has_command();
  }
}
void RobotCommand_Request::set_allocated_component_based_command(::rb::api::ComponentBasedCommand_Request* component_based_command) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_command();
  if (component_based_command) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(component_based_command)->GetArena();
    if (message_arena != submessage_arena) {
      component_based_command = ::google::protobuf::internal::GetOwnedMessage(message_arena, component_based_command, submessage_arena);
    }
    set_has_component_based_command();
    _impl_.command_.component_based_command_ = component_based_command;
  }
  // @@protoc_insertion_point(field_set_allocated:rb.api.RobotCommand.Request.component_based_command)
}
void RobotCommand_Request::clear_component_based_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (command_case() == kComponentBasedCommand) {
    if (GetArena() == nullptr) {
      delete _impl_.command_.component_based_command_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.command_.component_based_command_);
    }
    clear_has_command();
  }
}
void RobotCommand_Request::set_allocated_jog_command(::rb::api::JogCommand_Request* jog_command) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_command();
  if (jog_command) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(jog_command)->GetArena();
    if (message_arena != submessage_arena) {
      jog_command = ::google::protobuf::internal::GetOwnedMessage(message_arena, jog_command, submessage_arena);
    }
    set_has_jog_command();
    _impl_.command_.jog_command_ = jog_command;
  }
  // @@protoc_insertion_point(field_set_allocated:rb.api.RobotCommand.Request.jog_command)
}
void RobotCommand_Request::clear_jog_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (command_case() == kJogCommand) {
    if (GetArena() == nullptr) {
      delete _impl_.command_.jog_command_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.command_.jog_command_);
    }
    clear_has_command();
  }
}
RobotCommand_Request::RobotCommand_Request(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.RobotCommand.Request)
}
inline PROTOBUF_NDEBUG_INLINE RobotCommand_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::RobotCommand_Request& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        command_{},
        _oneof_case_{from._oneof_case_[0]} {}

RobotCommand_Request::RobotCommand_Request(
    ::google::protobuf::Arena* arena,
    const RobotCommand_Request& from)
    : ::google::protobuf::Message(arena) {
  RobotCommand_Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.command_header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::CommandHeader_Request>(
                              arena, *from._impl_.command_header_)
                        : nullptr;
  switch (command_case()) {
    case COMMAND_NOT_SET:
      break;
      case kWholeBodyCommand:
        _impl_.command_.whole_body_command_ = ::google::protobuf::Message::CopyConstruct<::rb::api::WholeBodyCommand_Request>(arena, *from._impl_.command_.whole_body_command_);
        break;
      case kComponentBasedCommand:
        _impl_.command_.component_based_command_ = ::google::protobuf::Message::CopyConstruct<::rb::api::ComponentBasedCommand_Request>(arena, *from._impl_.command_.component_based_command_);
        break;
      case kJogCommand:
        _impl_.command_.jog_command_ = ::google::protobuf::Message::CopyConstruct<::rb::api::JogCommand_Request>(arena, *from._impl_.command_.jog_command_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:rb.api.RobotCommand.Request)
}
inline PROTOBUF_NDEBUG_INLINE RobotCommand_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        command_{},
        _oneof_case_{} {}

inline void RobotCommand_Request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.command_header_ = {};
}
RobotCommand_Request::~RobotCommand_Request() {
  // @@protoc_insertion_point(destructor:rb.api.RobotCommand.Request)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RobotCommand_Request::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.command_header_;
  if (has_command()) {
    clear_command();
  }
  _impl_.~Impl_();
}

void RobotCommand_Request::clear_command() {
// @@protoc_insertion_point(one_of_clear_start:rb.api.RobotCommand.Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (command_case()) {
    case kWholeBodyCommand: {
      if (GetArena() == nullptr) {
        delete _impl_.command_.whole_body_command_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.command_.whole_body_command_);
      }
      break;
    }
    case kComponentBasedCommand: {
      if (GetArena() == nullptr) {
        delete _impl_.command_.component_based_command_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.command_.component_based_command_);
      }
      break;
    }
    case kJogCommand: {
      if (GetArena() == nullptr) {
        delete _impl_.command_.jog_command_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.command_.jog_command_);
      }
      break;
    }
    case COMMAND_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = COMMAND_NOT_SET;
}


const ::google::protobuf::MessageLite::ClassData*
RobotCommand_Request::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RobotCommand_Request, _impl_._cached_size_),
              false,
          },
          &RobotCommand_Request::MergeImpl,
          &RobotCommand_Request::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 4, 0, 2> RobotCommand_Request::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RobotCommand_Request, _impl_._has_bits_),
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RobotCommand_Request_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::RobotCommand_Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .rb.api.CommandHeader.Request command_header = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RobotCommand_Request, _impl_.command_header_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rb.api.CommandHeader.Request command_header = 1;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Request, _impl_.command_header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.WholeBodyCommand.Request whole_body_command = 2;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Request, _impl_.command_.whole_body_command_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.ComponentBasedCommand.Request component_based_command = 3;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Request, _impl_.command_.component_based_command_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.JogCommand.Request jog_command = 4;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Request, _impl_.command_.jog_command_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::rb::api::CommandHeader_Request>()},
    {::_pbi::TcParser::GetTable<::rb::api::WholeBodyCommand_Request>()},
    {::_pbi::TcParser::GetTable<::rb::api::ComponentBasedCommand_Request>()},
    {::_pbi::TcParser::GetTable<::rb::api::JogCommand_Request>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void RobotCommand_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.RobotCommand.Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.command_header_ != nullptr);
    _impl_.command_header_->Clear();
  }
  clear_command();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RobotCommand_Request::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.RobotCommand.Request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .rb.api.CommandHeader.Request command_header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.command_header_, _impl_.command_header_->GetCachedSize(), target, stream);
  }

  switch (command_case()) {
    case kWholeBodyCommand: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *_impl_.command_.whole_body_command_, _impl_.command_.whole_body_command_->GetCachedSize(), target, stream);
      break;
    }
    case kComponentBasedCommand: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *_impl_.command_.component_based_command_, _impl_.command_.component_based_command_->GetCachedSize(), target, stream);
      break;
    }
    case kJogCommand: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *_impl_.command_.jog_command_, _impl_.command_.jog_command_->GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.RobotCommand.Request)
  return target;
}

::size_t RobotCommand_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.RobotCommand.Request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .rb.api.CommandHeader.Request command_header = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.command_header_);
  }

  switch (command_case()) {
    // .rb.api.WholeBodyCommand.Request whole_body_command = 2;
    case kWholeBodyCommand: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.command_.whole_body_command_);
      break;
    }
    // .rb.api.ComponentBasedCommand.Request component_based_command = 3;
    case kComponentBasedCommand: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.command_.component_based_command_);
      break;
    }
    // .rb.api.JogCommand.Request jog_command = 4;
    case kJogCommand: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.command_.jog_command_);
      break;
    }
    case COMMAND_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RobotCommand_Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RobotCommand_Request*>(&to_msg);
  auto& from = static_cast<const RobotCommand_Request&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.RobotCommand.Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.command_header_ != nullptr);
    if (_this->_impl_.command_header_ == nullptr) {
      _this->_impl_.command_header_ =
          ::google::protobuf::Message::CopyConstruct<::rb::api::CommandHeader_Request>(arena, *from._impl_.command_header_);
    } else {
      _this->_impl_.command_header_->MergeFrom(*from._impl_.command_header_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_command();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kWholeBodyCommand: {
        if (oneof_needs_init) {
          _this->_impl_.command_.whole_body_command_ =
              ::google::protobuf::Message::CopyConstruct<::rb::api::WholeBodyCommand_Request>(arena, *from._impl_.command_.whole_body_command_);
        } else {
          _this->_impl_.command_.whole_body_command_->MergeFrom(from._internal_whole_body_command());
        }
        break;
      }
      case kComponentBasedCommand: {
        if (oneof_needs_init) {
          _this->_impl_.command_.component_based_command_ =
              ::google::protobuf::Message::CopyConstruct<::rb::api::ComponentBasedCommand_Request>(arena, *from._impl_.command_.component_based_command_);
        } else {
          _this->_impl_.command_.component_based_command_->MergeFrom(from._internal_component_based_command());
        }
        break;
      }
      case kJogCommand: {
        if (oneof_needs_init) {
          _this->_impl_.command_.jog_command_ =
              ::google::protobuf::Message::CopyConstruct<::rb::api::JogCommand_Request>(arena, *from._impl_.command_.jog_command_);
        } else {
          _this->_impl_.command_.jog_command_->MergeFrom(from._internal_jog_command());
        }
        break;
      }
      case COMMAND_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RobotCommand_Request::CopyFrom(const RobotCommand_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.RobotCommand.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RobotCommand_Request::InternalSwap(RobotCommand_Request* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.command_header_, other->_impl_.command_header_);
  swap(_impl_.command_, other->_impl_.command_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata RobotCommand_Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RobotCommand_Feedback::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RobotCommand_Feedback>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::rb::api::RobotCommand_Feedback, _impl_._oneof_case_);
};

void RobotCommand_Feedback::clear_command_header_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.command_header_feedback_ != nullptr) _impl_.command_header_feedback_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void RobotCommand_Feedback::set_allocated_whole_body_command_feedback(::rb::api::WholeBodyCommand_Feedback* whole_body_command_feedback) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_feedback();
  if (whole_body_command_feedback) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(whole_body_command_feedback)->GetArena();
    if (message_arena != submessage_arena) {
      whole_body_command_feedback = ::google::protobuf::internal::GetOwnedMessage(message_arena, whole_body_command_feedback, submessage_arena);
    }
    set_has_whole_body_command_feedback();
    _impl_.feedback_.whole_body_command_feedback_ = whole_body_command_feedback;
  }
  // @@protoc_insertion_point(field_set_allocated:rb.api.RobotCommand.Feedback.whole_body_command_feedback)
}
void RobotCommand_Feedback::clear_whole_body_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (feedback_case() == kWholeBodyCommandFeedback) {
    if (GetArena() == nullptr) {
      delete _impl_.feedback_.whole_body_command_feedback_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.feedback_.whole_body_command_feedback_);
    }
    clear_has_feedback();
  }
}
void RobotCommand_Feedback::set_allocated_component_based_command_feedback(::rb::api::ComponentBasedCommand_Feedback* component_based_command_feedback) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_feedback();
  if (component_based_command_feedback) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(component_based_command_feedback)->GetArena();
    if (message_arena != submessage_arena) {
      component_based_command_feedback = ::google::protobuf::internal::GetOwnedMessage(message_arena, component_based_command_feedback, submessage_arena);
    }
    set_has_component_based_command_feedback();
    _impl_.feedback_.component_based_command_feedback_ = component_based_command_feedback;
  }
  // @@protoc_insertion_point(field_set_allocated:rb.api.RobotCommand.Feedback.component_based_command_feedback)
}
void RobotCommand_Feedback::clear_component_based_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (feedback_case() == kComponentBasedCommandFeedback) {
    if (GetArena() == nullptr) {
      delete _impl_.feedback_.component_based_command_feedback_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.feedback_.component_based_command_feedback_);
    }
    clear_has_feedback();
  }
}
void RobotCommand_Feedback::set_allocated_jog_command_feedback(::rb::api::JogCommand_Feedback* jog_command_feedback) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_feedback();
  if (jog_command_feedback) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(jog_command_feedback)->GetArena();
    if (message_arena != submessage_arena) {
      jog_command_feedback = ::google::protobuf::internal::GetOwnedMessage(message_arena, jog_command_feedback, submessage_arena);
    }
    set_has_jog_command_feedback();
    _impl_.feedback_.jog_command_feedback_ = jog_command_feedback;
  }
  // @@protoc_insertion_point(field_set_allocated:rb.api.RobotCommand.Feedback.jog_command_feedback)
}
void RobotCommand_Feedback::clear_jog_command_feedback() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (feedback_case() == kJogCommandFeedback) {
    if (GetArena() == nullptr) {
      delete _impl_.feedback_.jog_command_feedback_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.feedback_.jog_command_feedback_);
    }
    clear_has_feedback();
  }
}
RobotCommand_Feedback::RobotCommand_Feedback(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.RobotCommand.Feedback)
}
inline PROTOBUF_NDEBUG_INLINE RobotCommand_Feedback::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::RobotCommand_Feedback& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        feedback_{},
        _oneof_case_{from._oneof_case_[0]} {}

RobotCommand_Feedback::RobotCommand_Feedback(
    ::google::protobuf::Arena* arena,
    const RobotCommand_Feedback& from)
    : ::google::protobuf::Message(arena) {
  RobotCommand_Feedback* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.command_header_feedback_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::CommandHeader_Feedback>(
                              arena, *from._impl_.command_header_feedback_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, status_),
           offsetof(Impl_, finish_code_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::finish_code_));
  switch (feedback_case()) {
    case FEEDBACK_NOT_SET:
      break;
      case kWholeBodyCommandFeedback:
        _impl_.feedback_.whole_body_command_feedback_ = ::google::protobuf::Message::CopyConstruct<::rb::api::WholeBodyCommand_Feedback>(arena, *from._impl_.feedback_.whole_body_command_feedback_);
        break;
      case kComponentBasedCommandFeedback:
        _impl_.feedback_.component_based_command_feedback_ = ::google::protobuf::Message::CopyConstruct<::rb::api::ComponentBasedCommand_Feedback>(arena, *from._impl_.feedback_.component_based_command_feedback_);
        break;
      case kJogCommandFeedback:
        _impl_.feedback_.jog_command_feedback_ = ::google::protobuf::Message::CopyConstruct<::rb::api::JogCommand_Feedback>(arena, *from._impl_.feedback_.jog_command_feedback_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:rb.api.RobotCommand.Feedback)
}
inline PROTOBUF_NDEBUG_INLINE RobotCommand_Feedback::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        feedback_{},
        _oneof_case_{} {}

inline void RobotCommand_Feedback::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_header_feedback_),
           0,
           offsetof(Impl_, finish_code_) -
               offsetof(Impl_, command_header_feedback_) +
               sizeof(Impl_::finish_code_));
}
RobotCommand_Feedback::~RobotCommand_Feedback() {
  // @@protoc_insertion_point(destructor:rb.api.RobotCommand.Feedback)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RobotCommand_Feedback::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.command_header_feedback_;
  if (has_feedback()) {
    clear_feedback();
  }
  _impl_.~Impl_();
}

void RobotCommand_Feedback::clear_feedback() {
// @@protoc_insertion_point(one_of_clear_start:rb.api.RobotCommand.Feedback)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (feedback_case()) {
    case kWholeBodyCommandFeedback: {
      if (GetArena() == nullptr) {
        delete _impl_.feedback_.whole_body_command_feedback_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.feedback_.whole_body_command_feedback_);
      }
      break;
    }
    case kComponentBasedCommandFeedback: {
      if (GetArena() == nullptr) {
        delete _impl_.feedback_.component_based_command_feedback_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.feedback_.component_based_command_feedback_);
      }
      break;
    }
    case kJogCommandFeedback: {
      if (GetArena() == nullptr) {
        delete _impl_.feedback_.jog_command_feedback_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.feedback_.jog_command_feedback_);
      }
      break;
    }
    case FEEDBACK_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = FEEDBACK_NOT_SET;
}


const ::google::protobuf::MessageLite::ClassData*
RobotCommand_Feedback::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_._cached_size_),
              false,
          },
          &RobotCommand_Feedback::MergeImpl,
          &RobotCommand_Feedback::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 6, 4, 0, 2> RobotCommand_Feedback::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_._has_bits_),
    0, // no _extensions_
    11, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965744,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RobotCommand_Feedback_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::RobotCommand_Feedback>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .rb.api.CommandHeader.Feedback command_header_feedback = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.command_header_feedback_)}},
    // .rb.api.RobotCommand.Feedback.Status status = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RobotCommand_Feedback, _impl_.status_), 63>(),
     {80, 63, 0, PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.status_)}},
    // .rb.api.RobotCommand.Feedback.FinishCode finish_code = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RobotCommand_Feedback, _impl_.finish_code_), 63>(),
     {88, 63, 0, PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.finish_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rb.api.CommandHeader.Feedback command_header_feedback = 1;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.command_header_feedback_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.WholeBodyCommand.Feedback whole_body_command_feedback = 2;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.feedback_.whole_body_command_feedback_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.ComponentBasedCommand.Feedback component_based_command_feedback = 3;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.feedback_.component_based_command_feedback_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.JogCommand.Feedback jog_command_feedback = 4;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.feedback_.jog_command_feedback_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.RobotCommand.Feedback.Status status = 10;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.status_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .rb.api.RobotCommand.Feedback.FinishCode finish_code = 11;
    {PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.finish_code_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }}, {{
    {::_pbi::TcParser::GetTable<::rb::api::CommandHeader_Feedback>()},
    {::_pbi::TcParser::GetTable<::rb::api::WholeBodyCommand_Feedback>()},
    {::_pbi::TcParser::GetTable<::rb::api::ComponentBasedCommand_Feedback>()},
    {::_pbi::TcParser::GetTable<::rb::api::JogCommand_Feedback>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void RobotCommand_Feedback::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.RobotCommand.Feedback)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.command_header_feedback_ != nullptr);
    _impl_.command_header_feedback_->Clear();
  }
  ::memset(&_impl_.status_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.finish_code_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.finish_code_));
  clear_feedback();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RobotCommand_Feedback::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.RobotCommand.Feedback)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .rb.api.CommandHeader.Feedback command_header_feedback = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.command_header_feedback_, _impl_.command_header_feedback_->GetCachedSize(), target, stream);
  }

  switch (feedback_case()) {
    case kWholeBodyCommandFeedback: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *_impl_.feedback_.whole_body_command_feedback_, _impl_.feedback_.whole_body_command_feedback_->GetCachedSize(), target, stream);
      break;
    }
    case kComponentBasedCommandFeedback: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *_impl_.feedback_.component_based_command_feedback_, _impl_.feedback_.component_based_command_feedback_->GetCachedSize(), target, stream);
      break;
    }
    case kJogCommandFeedback: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *_impl_.feedback_.jog_command_feedback_, _impl_.feedback_.jog_command_feedback_->GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  // .rb.api.RobotCommand.Feedback.Status status = 10;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        10, this->_internal_status(), target);
  }

  // .rb.api.RobotCommand.Feedback.FinishCode finish_code = 11;
  if (this->_internal_finish_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        11, this->_internal_finish_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.RobotCommand.Feedback)
  return target;
}

::size_t RobotCommand_Feedback::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.RobotCommand.Feedback)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // .rb.api.CommandHeader.Feedback command_header_feedback = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.command_header_feedback_);
  }

  // .rb.api.RobotCommand.Feedback.Status status = 10;
  if (this->_internal_status() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  // .rb.api.RobotCommand.Feedback.FinishCode finish_code = 11;
  if (this->_internal_finish_code() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_finish_code());
  }

  switch (feedback_case()) {
    // .rb.api.WholeBodyCommand.Feedback whole_body_command_feedback = 2;
    case kWholeBodyCommandFeedback: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.feedback_.whole_body_command_feedback_);
      break;
    }
    // .rb.api.ComponentBasedCommand.Feedback component_based_command_feedback = 3;
    case kComponentBasedCommandFeedback: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.feedback_.component_based_command_feedback_);
      break;
    }
    // .rb.api.JogCommand.Feedback jog_command_feedback = 4;
    case kJogCommandFeedback: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.feedback_.jog_command_feedback_);
      break;
    }
    case FEEDBACK_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RobotCommand_Feedback::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RobotCommand_Feedback*>(&to_msg);
  auto& from = static_cast<const RobotCommand_Feedback&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.RobotCommand.Feedback)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.command_header_feedback_ != nullptr);
    if (_this->_impl_.command_header_feedback_ == nullptr) {
      _this->_impl_.command_header_feedback_ =
          ::google::protobuf::Message::CopyConstruct<::rb::api::CommandHeader_Feedback>(arena, *from._impl_.command_header_feedback_);
    } else {
      _this->_impl_.command_header_feedback_->MergeFrom(*from._impl_.command_header_feedback_);
    }
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  if (from._internal_finish_code() != 0) {
    _this->_impl_.finish_code_ = from._impl_.finish_code_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_feedback();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kWholeBodyCommandFeedback: {
        if (oneof_needs_init) {
          _this->_impl_.feedback_.whole_body_command_feedback_ =
              ::google::protobuf::Message::CopyConstruct<::rb::api::WholeBodyCommand_Feedback>(arena, *from._impl_.feedback_.whole_body_command_feedback_);
        } else {
          _this->_impl_.feedback_.whole_body_command_feedback_->MergeFrom(from._internal_whole_body_command_feedback());
        }
        break;
      }
      case kComponentBasedCommandFeedback: {
        if (oneof_needs_init) {
          _this->_impl_.feedback_.component_based_command_feedback_ =
              ::google::protobuf::Message::CopyConstruct<::rb::api::ComponentBasedCommand_Feedback>(arena, *from._impl_.feedback_.component_based_command_feedback_);
        } else {
          _this->_impl_.feedback_.component_based_command_feedback_->MergeFrom(from._internal_component_based_command_feedback());
        }
        break;
      }
      case kJogCommandFeedback: {
        if (oneof_needs_init) {
          _this->_impl_.feedback_.jog_command_feedback_ =
              ::google::protobuf::Message::CopyConstruct<::rb::api::JogCommand_Feedback>(arena, *from._impl_.feedback_.jog_command_feedback_);
        } else {
          _this->_impl_.feedback_.jog_command_feedback_->MergeFrom(from._internal_jog_command_feedback());
        }
        break;
      }
      case FEEDBACK_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RobotCommand_Feedback::CopyFrom(const RobotCommand_Feedback& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.RobotCommand.Feedback)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RobotCommand_Feedback::InternalSwap(RobotCommand_Feedback* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.finish_code_)
      + sizeof(RobotCommand_Feedback::_impl_.finish_code_)
      - PROTOBUF_FIELD_OFFSET(RobotCommand_Feedback, _impl_.command_header_feedback_)>(
          reinterpret_cast<char*>(&_impl_.command_header_feedback_),
          reinterpret_cast<char*>(&other->_impl_.command_header_feedback_));
  swap(_impl_.feedback_, other->_impl_.feedback_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata RobotCommand_Feedback::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RobotCommand::_Internal {
 public:
};

RobotCommand::RobotCommand(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:rb.api.RobotCommand)
}
RobotCommand::RobotCommand(
    ::google::protobuf::Arena* arena,
    const RobotCommand& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  RobotCommand* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:rb.api.RobotCommand)
}

const ::google::protobuf::MessageLite::ClassData*
RobotCommand::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RobotCommand, _impl_._cached_size_),
              false,
          },
          &RobotCommand::MergeImpl,
          &RobotCommand::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> RobotCommand::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RobotCommand_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::RobotCommand>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};









::google::protobuf::Metadata RobotCommand::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RobotCommandRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RobotCommandRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_._has_bits_);
};

void RobotCommandRequest::clear_request_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_header_ != nullptr) _impl_.request_header_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
RobotCommandRequest::RobotCommandRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.RobotCommandRequest)
}
inline PROTOBUF_NDEBUG_INLINE RobotCommandRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::RobotCommandRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

RobotCommandRequest::RobotCommandRequest(
    ::google::protobuf::Arena* arena,
    const RobotCommandRequest& from)
    : ::google::protobuf::Message(arena) {
  RobotCommandRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.request_header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::RequestHeader>(
                              arena, *from._impl_.request_header_)
                        : nullptr;
  _impl_.robot_command_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::RobotCommand_Request>(
                              arena, *from._impl_.robot_command_)
                        : nullptr;
  _impl_.priority_ = from._impl_.priority_;

  // @@protoc_insertion_point(copy_constructor:rb.api.RobotCommandRequest)
}
inline PROTOBUF_NDEBUG_INLINE RobotCommandRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RobotCommandRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, request_header_),
           0,
           offsetof(Impl_, priority_) -
               offsetof(Impl_, request_header_) +
               sizeof(Impl_::priority_));
}
RobotCommandRequest::~RobotCommandRequest() {
  // @@protoc_insertion_point(destructor:rb.api.RobotCommandRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RobotCommandRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.request_header_;
  delete _impl_.robot_command_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RobotCommandRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_._cached_size_),
              false,
          },
          &RobotCommandRequest::MergeImpl,
          &RobotCommandRequest::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> RobotCommandRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RobotCommandRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::RobotCommandRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .rb.api.RequestHeader request_header = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_.request_header_)}},
    // .rb.api.RobotCommand.Request robot_command = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_.robot_command_)}},
    // int32 priority = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RobotCommandRequest, _impl_.priority_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_.priority_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rb.api.RequestHeader request_header = 1;
    {PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_.request_header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.RobotCommand.Request robot_command = 2;
    {PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_.robot_command_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 priority = 3;
    {PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_.priority_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::rb::api::RequestHeader>()},
    {::_pbi::TcParser::GetTable<::rb::api::RobotCommand_Request>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void RobotCommandRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.RobotCommandRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.request_header_ != nullptr);
      _impl_.request_header_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.robot_command_ != nullptr);
      _impl_.robot_command_->Clear();
    }
  }
  _impl_.priority_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RobotCommandRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.RobotCommandRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .rb.api.RequestHeader request_header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.request_header_, _impl_.request_header_->GetCachedSize(), target, stream);
  }

  // .rb.api.RobotCommand.Request robot_command = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.robot_command_, _impl_.robot_command_->GetCachedSize(), target, stream);
  }

  // int32 priority = 3;
  if (this->_internal_priority() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_priority(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.RobotCommandRequest)
  return target;
}

::size_t RobotCommandRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.RobotCommandRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .rb.api.RequestHeader request_header = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.request_header_);
    }

    // .rb.api.RobotCommand.Request robot_command = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.robot_command_);
    }

  }
  // int32 priority = 3;
  if (this->_internal_priority() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_priority());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RobotCommandRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RobotCommandRequest*>(&to_msg);
  auto& from = static_cast<const RobotCommandRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.RobotCommandRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.request_header_ != nullptr);
      if (_this->_impl_.request_header_ == nullptr) {
        _this->_impl_.request_header_ =
            ::google::protobuf::Message::CopyConstruct<::rb::api::RequestHeader>(arena, *from._impl_.request_header_);
      } else {
        _this->_impl_.request_header_->MergeFrom(*from._impl_.request_header_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.robot_command_ != nullptr);
      if (_this->_impl_.robot_command_ == nullptr) {
        _this->_impl_.robot_command_ =
            ::google::protobuf::Message::CopyConstruct<::rb::api::RobotCommand_Request>(arena, *from._impl_.robot_command_);
      } else {
        _this->_impl_.robot_command_->MergeFrom(*from._impl_.robot_command_);
      }
    }
  }
  if (from._internal_priority() != 0) {
    _this->_impl_.priority_ = from._impl_.priority_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RobotCommandRequest::CopyFrom(const RobotCommandRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.RobotCommandRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RobotCommandRequest::InternalSwap(RobotCommandRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_.priority_)
      + sizeof(RobotCommandRequest::_impl_.priority_)
      - PROTOBUF_FIELD_OFFSET(RobotCommandRequest, _impl_.request_header_)>(
          reinterpret_cast<char*>(&_impl_.request_header_),
          reinterpret_cast<char*>(&other->_impl_.request_header_));
}

::google::protobuf::Metadata RobotCommandRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RobotCommandResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RobotCommandResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_._has_bits_);
};

void RobotCommandResponse::clear_response_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_header_ != nullptr) _impl_.response_header_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
RobotCommandResponse::RobotCommandResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rb.api.RobotCommandResponse)
}
inline PROTOBUF_NDEBUG_INLINE RobotCommandResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rb::api::RobotCommandResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

RobotCommandResponse::RobotCommandResponse(
    ::google::protobuf::Arena* arena,
    const RobotCommandResponse& from)
    : ::google::protobuf::Message(arena) {
  RobotCommandResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.response_header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::ResponseHeader>(
                              arena, *from._impl_.response_header_)
                        : nullptr;
  _impl_.feedback_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::rb::api::RobotCommand_Feedback>(
                              arena, *from._impl_.feedback_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:rb.api.RobotCommandResponse)
}
inline PROTOBUF_NDEBUG_INLINE RobotCommandResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RobotCommandResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, response_header_),
           0,
           offsetof(Impl_, feedback_) -
               offsetof(Impl_, response_header_) +
               sizeof(Impl_::feedback_));
}
RobotCommandResponse::~RobotCommandResponse() {
  // @@protoc_insertion_point(destructor:rb.api.RobotCommandResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RobotCommandResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.response_header_;
  delete _impl_.feedback_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RobotCommandResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_._cached_size_),
              false,
          },
          &RobotCommandResponse::MergeImpl,
          &RobotCommandResponse::kDescriptorMethods,
          &descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> RobotCommandResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RobotCommandResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rb::api::RobotCommandResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .rb.api.RobotCommand.Feedback feedback = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_.feedback_)}},
    // .rb.api.ResponseHeader response_header = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_.response_header_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rb.api.ResponseHeader response_header = 1;
    {PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_.response_header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rb.api.RobotCommand.Feedback feedback = 2;
    {PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_.feedback_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::rb::api::ResponseHeader>()},
    {::_pbi::TcParser::GetTable<::rb::api::RobotCommand_Feedback>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void RobotCommandResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:rb.api.RobotCommandResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.response_header_ != nullptr);
      _impl_.response_header_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.feedback_ != nullptr);
      _impl_.feedback_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RobotCommandResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rb.api.RobotCommandResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .rb.api.ResponseHeader response_header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.response_header_, _impl_.response_header_->GetCachedSize(), target, stream);
  }

  // .rb.api.RobotCommand.Feedback feedback = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.feedback_, _impl_.feedback_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rb.api.RobotCommandResponse)
  return target;
}

::size_t RobotCommandResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rb.api.RobotCommandResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .rb.api.ResponseHeader response_header = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.response_header_);
    }

    // .rb.api.RobotCommand.Feedback feedback = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.feedback_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RobotCommandResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RobotCommandResponse*>(&to_msg);
  auto& from = static_cast<const RobotCommandResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rb.api.RobotCommandResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.response_header_ != nullptr);
      if (_this->_impl_.response_header_ == nullptr) {
        _this->_impl_.response_header_ =
            ::google::protobuf::Message::CopyConstruct<::rb::api::ResponseHeader>(arena, *from._impl_.response_header_);
      } else {
        _this->_impl_.response_header_->MergeFrom(*from._impl_.response_header_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.feedback_ != nullptr);
      if (_this->_impl_.feedback_ == nullptr) {
        _this->_impl_.feedback_ =
            ::google::protobuf::Message::CopyConstruct<::rb::api::RobotCommand_Feedback>(arena, *from._impl_.feedback_);
      } else {
        _this->_impl_.feedback_->MergeFrom(*from._impl_.feedback_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RobotCommandResponse::CopyFrom(const RobotCommandResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rb.api.RobotCommandResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RobotCommandResponse::InternalSwap(RobotCommandResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_.feedback_)
      + sizeof(RobotCommandResponse::_impl_.feedback_)
      - PROTOBUF_FIELD_OFFSET(RobotCommandResponse, _impl_.response_header_)>(
          reinterpret_cast<char*>(&_impl_.response_header_),
          reinterpret_cast<char*>(&other->_impl_.response_header_));
}

::google::protobuf::Metadata RobotCommandResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace rb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rb_2fapi_2frobot_5fcommand_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
