// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rb/api/robot_state_service.proto
#ifndef GRPC_rb_2fapi_2frobot_5fstate_5fservice_2eproto__INCLUDED
#define GRPC_rb_2fapi_2frobot_5fstate_5fservice_2eproto__INCLUDED

#include "rb/api/robot_state_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace rb {
namespace api {

class RobotStateService final {
 public:
  static constexpr char const* service_full_name() {
    return "rb.api.RobotStateService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::rb::api::GetRobotStateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotStateResponse>> AsyncGetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotStateResponse>>(AsyncGetRobotStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotStateResponse>> PrepareAsyncGetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotStateResponse>>(PrepareAsyncGetRobotStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::rb::api::GetRobotStateStreamResponse>> GetRobotStateStream(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::rb::api::GetRobotStateStreamResponse>>(GetRobotStateStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rb::api::GetRobotStateStreamResponse>> AsyncGetRobotStateStream(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rb::api::GetRobotStateStreamResponse>>(AsyncGetRobotStateStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rb::api::GetRobotStateStreamResponse>> PrepareAsyncGetRobotStateStream(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rb::api::GetRobotStateStreamResponse>>(PrepareAsyncGetRobotStateStreamRaw(context, request, cq));
    }
    virtual ::grpc::Status GetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::rb::api::GetControlManagerStateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetControlManagerStateResponse>> AsyncGetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetControlManagerStateResponse>>(AsyncGetControlManagerStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetControlManagerStateResponse>> PrepareAsyncGetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetControlManagerStateResponse>>(PrepareAsyncGetControlManagerStateRaw(context, request, cq));
    }
    virtual ::grpc::Status ResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::rb::api::ResetOdometryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ResetOdometryResponse>> AsyncResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ResetOdometryResponse>>(AsyncResetOdometryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ResetOdometryResponse>> PrepareAsyncResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ResetOdometryResponse>>(PrepareAsyncResetOdometryRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest* request, ::rb::api::GetRobotStateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest* request, ::rb::api::GetRobotStateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetRobotStateStream(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest* request, ::grpc::ClientReadReactor< ::rb::api::GetRobotStateStreamResponse>* reactor) = 0;
      virtual void GetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest* request, ::rb::api::GetControlManagerStateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest* request, ::rb::api::GetControlManagerStateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest* request, ::rb::api::ResetOdometryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest* request, ::rb::api::ResetOdometryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotStateResponse>* AsyncGetRobotStateRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetRobotStateResponse>* PrepareAsyncGetRobotStateRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::rb::api::GetRobotStateStreamResponse>* GetRobotStateStreamRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rb::api::GetRobotStateStreamResponse>* AsyncGetRobotStateStreamRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rb::api::GetRobotStateStreamResponse>* PrepareAsyncGetRobotStateStreamRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetControlManagerStateResponse>* AsyncGetControlManagerStateRaw(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::GetControlManagerStateResponse>* PrepareAsyncGetControlManagerStateRaw(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ResetOdometryResponse>* AsyncResetOdometryRaw(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rb::api::ResetOdometryResponse>* PrepareAsyncResetOdometryRaw(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::rb::api::GetRobotStateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotStateResponse>> AsyncGetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotStateResponse>>(AsyncGetRobotStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotStateResponse>> PrepareAsyncGetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotStateResponse>>(PrepareAsyncGetRobotStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::rb::api::GetRobotStateStreamResponse>> GetRobotStateStream(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::rb::api::GetRobotStateStreamResponse>>(GetRobotStateStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rb::api::GetRobotStateStreamResponse>> AsyncGetRobotStateStream(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rb::api::GetRobotStateStreamResponse>>(AsyncGetRobotStateStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rb::api::GetRobotStateStreamResponse>> PrepareAsyncGetRobotStateStream(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rb::api::GetRobotStateStreamResponse>>(PrepareAsyncGetRobotStateStreamRaw(context, request, cq));
    }
    ::grpc::Status GetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::rb::api::GetControlManagerStateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetControlManagerStateResponse>> AsyncGetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetControlManagerStateResponse>>(AsyncGetControlManagerStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetControlManagerStateResponse>> PrepareAsyncGetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::GetControlManagerStateResponse>>(PrepareAsyncGetControlManagerStateRaw(context, request, cq));
    }
    ::grpc::Status ResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::rb::api::ResetOdometryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ResetOdometryResponse>> AsyncResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ResetOdometryResponse>>(AsyncResetOdometryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ResetOdometryResponse>> PrepareAsyncResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rb::api::ResetOdometryResponse>>(PrepareAsyncResetOdometryRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest* request, ::rb::api::GetRobotStateResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRobotState(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest* request, ::rb::api::GetRobotStateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetRobotStateStream(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest* request, ::grpc::ClientReadReactor< ::rb::api::GetRobotStateStreamResponse>* reactor) override;
      void GetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest* request, ::rb::api::GetControlManagerStateResponse* response, std::function<void(::grpc::Status)>) override;
      void GetControlManagerState(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest* request, ::rb::api::GetControlManagerStateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest* request, ::rb::api::ResetOdometryResponse* response, std::function<void(::grpc::Status)>) override;
      void ResetOdometry(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest* request, ::rb::api::ResetOdometryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotStateResponse>* AsyncGetRobotStateRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetRobotStateResponse>* PrepareAsyncGetRobotStateRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::rb::api::GetRobotStateStreamResponse>* GetRobotStateStreamRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::rb::api::GetRobotStateStreamResponse>* AsyncGetRobotStateStreamRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::rb::api::GetRobotStateStreamResponse>* PrepareAsyncGetRobotStateStreamRaw(::grpc::ClientContext* context, const ::rb::api::GetRobotStateStreamRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetControlManagerStateResponse>* AsyncGetControlManagerStateRaw(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::GetControlManagerStateResponse>* PrepareAsyncGetControlManagerStateRaw(::grpc::ClientContext* context, const ::rb::api::GetControlManagerStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::ResetOdometryResponse>* AsyncResetOdometryRaw(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rb::api::ResetOdometryResponse>* PrepareAsyncResetOdometryRaw(::grpc::ClientContext* context, const ::rb::api::ResetOdometryRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetRobotState_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRobotStateStream_;
    const ::grpc::internal::RpcMethod rpcmethod_GetControlManagerState_;
    const ::grpc::internal::RpcMethod rpcmethod_ResetOdometry_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetRobotState(::grpc::ServerContext* context, const ::rb::api::GetRobotStateRequest* request, ::rb::api::GetRobotStateResponse* response);
    virtual ::grpc::Status GetRobotStateStream(::grpc::ServerContext* context, const ::rb::api::GetRobotStateStreamRequest* request, ::grpc::ServerWriter< ::rb::api::GetRobotStateStreamResponse>* writer);
    virtual ::grpc::Status GetControlManagerState(::grpc::ServerContext* context, const ::rb::api::GetControlManagerStateRequest* request, ::rb::api::GetControlManagerStateResponse* response);
    virtual ::grpc::Status ResetOdometry(::grpc::ServerContext* context, const ::rb::api::ResetOdometryRequest* request, ::rb::api::ResetOdometryResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRobotState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRobotState() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetRobotState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotState(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateRequest* /*request*/, ::rb::api::GetRobotStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotState(::grpc::ServerContext* context, ::rb::api::GetRobotStateRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::GetRobotStateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRobotStateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRobotStateStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetRobotStateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStateStream(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateStreamRequest* /*request*/, ::grpc::ServerWriter< ::rb::api::GetRobotStateStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotStateStream(::grpc::ServerContext* context, ::rb::api::GetRobotStateStreamRequest* request, ::grpc::ServerAsyncWriter< ::rb::api::GetRobotStateStreamResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetControlManagerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetControlManagerState() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetControlManagerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetControlManagerState(::grpc::ServerContext* /*context*/, const ::rb::api::GetControlManagerStateRequest* /*request*/, ::rb::api::GetControlManagerStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetControlManagerState(::grpc::ServerContext* context, ::rb::api::GetControlManagerStateRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::GetControlManagerStateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ResetOdometry : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ResetOdometry() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ResetOdometry() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetOdometry(::grpc::ServerContext* /*context*/, const ::rb::api::ResetOdometryRequest* /*request*/, ::rb::api::ResetOdometryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResetOdometry(::grpc::ServerContext* context, ::rb::api::ResetOdometryRequest* request, ::grpc::ServerAsyncResponseWriter< ::rb::api::ResetOdometryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetRobotState<WithAsyncMethod_GetRobotStateStream<WithAsyncMethod_GetControlManagerState<WithAsyncMethod_ResetOdometry<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetRobotState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRobotState() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::GetRobotStateRequest, ::rb::api::GetRobotStateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::GetRobotStateRequest* request, ::rb::api::GetRobotStateResponse* response) { return this->GetRobotState(context, request, response); }));}
    void SetMessageAllocatorFor_GetRobotState(
        ::grpc::MessageAllocator< ::rb::api::GetRobotStateRequest, ::rb::api::GetRobotStateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::GetRobotStateRequest, ::rb::api::GetRobotStateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRobotState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotState(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateRequest* /*request*/, ::rb::api::GetRobotStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRobotState(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::GetRobotStateRequest* /*request*/, ::rb::api::GetRobotStateResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRobotStateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRobotStateStream() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::rb::api::GetRobotStateStreamRequest, ::rb::api::GetRobotStateStreamResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::GetRobotStateStreamRequest* request) { return this->GetRobotStateStream(context, request); }));
    }
    ~WithCallbackMethod_GetRobotStateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStateStream(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateStreamRequest* /*request*/, ::grpc::ServerWriter< ::rb::api::GetRobotStateStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::rb::api::GetRobotStateStreamResponse>* GetRobotStateStream(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::GetRobotStateStreamRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetControlManagerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetControlManagerState() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::GetControlManagerStateRequest, ::rb::api::GetControlManagerStateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::GetControlManagerStateRequest* request, ::rb::api::GetControlManagerStateResponse* response) { return this->GetControlManagerState(context, request, response); }));}
    void SetMessageAllocatorFor_GetControlManagerState(
        ::grpc::MessageAllocator< ::rb::api::GetControlManagerStateRequest, ::rb::api::GetControlManagerStateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::GetControlManagerStateRequest, ::rb::api::GetControlManagerStateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetControlManagerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetControlManagerState(::grpc::ServerContext* /*context*/, const ::rb::api::GetControlManagerStateRequest* /*request*/, ::rb::api::GetControlManagerStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetControlManagerState(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::GetControlManagerStateRequest* /*request*/, ::rb::api::GetControlManagerStateResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ResetOdometry : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ResetOdometry() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::rb::api::ResetOdometryRequest, ::rb::api::ResetOdometryResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rb::api::ResetOdometryRequest* request, ::rb::api::ResetOdometryResponse* response) { return this->ResetOdometry(context, request, response); }));}
    void SetMessageAllocatorFor_ResetOdometry(
        ::grpc::MessageAllocator< ::rb::api::ResetOdometryRequest, ::rb::api::ResetOdometryResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rb::api::ResetOdometryRequest, ::rb::api::ResetOdometryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ResetOdometry() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetOdometry(::grpc::ServerContext* /*context*/, const ::rb::api::ResetOdometryRequest* /*request*/, ::rb::api::ResetOdometryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ResetOdometry(
      ::grpc::CallbackServerContext* /*context*/, const ::rb::api::ResetOdometryRequest* /*request*/, ::rb::api::ResetOdometryResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetRobotState<WithCallbackMethod_GetRobotStateStream<WithCallbackMethod_GetControlManagerState<WithCallbackMethod_ResetOdometry<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetRobotState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRobotState() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetRobotState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotState(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateRequest* /*request*/, ::rb::api::GetRobotStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRobotStateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRobotStateStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetRobotStateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStateStream(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateStreamRequest* /*request*/, ::grpc::ServerWriter< ::rb::api::GetRobotStateStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetControlManagerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetControlManagerState() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetControlManagerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetControlManagerState(::grpc::ServerContext* /*context*/, const ::rb::api::GetControlManagerStateRequest* /*request*/, ::rb::api::GetControlManagerStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ResetOdometry : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ResetOdometry() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ResetOdometry() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetOdometry(::grpc::ServerContext* /*context*/, const ::rb::api::ResetOdometryRequest* /*request*/, ::rb::api::ResetOdometryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRobotState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRobotState() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetRobotState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotState(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateRequest* /*request*/, ::rb::api::GetRobotStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRobotStateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRobotStateStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetRobotStateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStateStream(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateStreamRequest* /*request*/, ::grpc::ServerWriter< ::rb::api::GetRobotStateStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotStateStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetControlManagerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetControlManagerState() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetControlManagerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetControlManagerState(::grpc::ServerContext* /*context*/, const ::rb::api::GetControlManagerStateRequest* /*request*/, ::rb::api::GetControlManagerStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetControlManagerState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ResetOdometry : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ResetOdometry() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ResetOdometry() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetOdometry(::grpc::ServerContext* /*context*/, const ::rb::api::ResetOdometryRequest* /*request*/, ::rb::api::ResetOdometryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResetOdometry(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRobotState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRobotState() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRobotState(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRobotState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotState(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateRequest* /*request*/, ::rb::api::GetRobotStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRobotState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRobotStateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRobotStateStream() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->GetRobotStateStream(context, request); }));
    }
    ~WithRawCallbackMethod_GetRobotStateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStateStream(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateStreamRequest* /*request*/, ::grpc::ServerWriter< ::rb::api::GetRobotStateStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetRobotStateStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetControlManagerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetControlManagerState() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetControlManagerState(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetControlManagerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetControlManagerState(::grpc::ServerContext* /*context*/, const ::rb::api::GetControlManagerStateRequest* /*request*/, ::rb::api::GetControlManagerStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetControlManagerState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ResetOdometry : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ResetOdometry() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ResetOdometry(context, request, response); }));
    }
    ~WithRawCallbackMethod_ResetOdometry() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetOdometry(::grpc::ServerContext* /*context*/, const ::rb::api::ResetOdometryRequest* /*request*/, ::rb::api::ResetOdometryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ResetOdometry(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRobotState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRobotState() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::GetRobotStateRequest, ::rb::api::GetRobotStateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::GetRobotStateRequest, ::rb::api::GetRobotStateResponse>* streamer) {
                       return this->StreamedGetRobotState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRobotState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRobotState(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateRequest* /*request*/, ::rb::api::GetRobotStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRobotState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::GetRobotStateRequest,::rb::api::GetRobotStateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetControlManagerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetControlManagerState() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::GetControlManagerStateRequest, ::rb::api::GetControlManagerStateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::GetControlManagerStateRequest, ::rb::api::GetControlManagerStateResponse>* streamer) {
                       return this->StreamedGetControlManagerState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetControlManagerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetControlManagerState(::grpc::ServerContext* /*context*/, const ::rb::api::GetControlManagerStateRequest* /*request*/, ::rb::api::GetControlManagerStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetControlManagerState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::GetControlManagerStateRequest,::rb::api::GetControlManagerStateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ResetOdometry : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ResetOdometry() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rb::api::ResetOdometryRequest, ::rb::api::ResetOdometryResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rb::api::ResetOdometryRequest, ::rb::api::ResetOdometryResponse>* streamer) {
                       return this->StreamedResetOdometry(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ResetOdometry() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ResetOdometry(::grpc::ServerContext* /*context*/, const ::rb::api::ResetOdometryRequest* /*request*/, ::rb::api::ResetOdometryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedResetOdometry(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rb::api::ResetOdometryRequest,::rb::api::ResetOdometryResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetRobotState<WithStreamedUnaryMethod_GetControlManagerState<WithStreamedUnaryMethod_ResetOdometry<Service > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetRobotStateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetRobotStateStream() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::rb::api::GetRobotStateStreamRequest, ::rb::api::GetRobotStateStreamResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::rb::api::GetRobotStateStreamRequest, ::rb::api::GetRobotStateStreamResponse>* streamer) {
                       return this->StreamedGetRobotStateStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetRobotStateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRobotStateStream(::grpc::ServerContext* /*context*/, const ::rb::api::GetRobotStateStreamRequest* /*request*/, ::grpc::ServerWriter< ::rb::api::GetRobotStateStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetRobotStateStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::rb::api::GetRobotStateStreamRequest,::rb::api::GetRobotStateStreamResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetRobotStateStream<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetRobotState<WithSplitStreamingMethod_GetRobotStateStream<WithStreamedUnaryMethod_GetControlManagerState<WithStreamedUnaryMethod_ResetOdometry<Service > > > > StreamedService;
};

}  // namespace api
}  // namespace rb


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_rb_2fapi_2frobot_5fstate_5fservice_2eproto__INCLUDED
