// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rb/api/serial_service.proto

#include "rb/api/serial_service.pb.h"
#include "rb/api/serial_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rb {
namespace api {

static const char* SerialService_method_names[] = {
  "/rb.api.SerialService/GetSerialDeviceList",
  "/rb.api.SerialService/OpenSerialStream",
};

std::unique_ptr< SerialService::Stub> SerialService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SerialService::Stub> stub(new SerialService::Stub(channel, options));
  return stub;
}

SerialService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetSerialDeviceList_(SerialService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OpenSerialStream_(SerialService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status SerialService::Stub::GetSerialDeviceList(::grpc::ClientContext* context, const ::rb::api::GetSerialDeviceListRequest& request, ::rb::api::GetSerialDeviceListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rb::api::GetSerialDeviceListRequest, ::rb::api::GetSerialDeviceListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSerialDeviceList_, context, request, response);
}

void SerialService::Stub::async::GetSerialDeviceList(::grpc::ClientContext* context, const ::rb::api::GetSerialDeviceListRequest* request, ::rb::api::GetSerialDeviceListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rb::api::GetSerialDeviceListRequest, ::rb::api::GetSerialDeviceListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSerialDeviceList_, context, request, response, std::move(f));
}

void SerialService::Stub::async::GetSerialDeviceList(::grpc::ClientContext* context, const ::rb::api::GetSerialDeviceListRequest* request, ::rb::api::GetSerialDeviceListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSerialDeviceList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rb::api::GetSerialDeviceListResponse>* SerialService::Stub::PrepareAsyncGetSerialDeviceListRaw(::grpc::ClientContext* context, const ::rb::api::GetSerialDeviceListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rb::api::GetSerialDeviceListResponse, ::rb::api::GetSerialDeviceListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSerialDeviceList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rb::api::GetSerialDeviceListResponse>* SerialService::Stub::AsyncGetSerialDeviceListRaw(::grpc::ClientContext* context, const ::rb::api::GetSerialDeviceListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSerialDeviceListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::rb::api::OpenSerialStreamRequest, ::rb::api::OpenSerialStreamResponse>* SerialService::Stub::OpenSerialStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::rb::api::OpenSerialStreamRequest, ::rb::api::OpenSerialStreamResponse>::Create(channel_.get(), rpcmethod_OpenSerialStream_, context);
}

void SerialService::Stub::async::OpenSerialStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::rb::api::OpenSerialStreamRequest,::rb::api::OpenSerialStreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::rb::api::OpenSerialStreamRequest,::rb::api::OpenSerialStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_OpenSerialStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::rb::api::OpenSerialStreamRequest, ::rb::api::OpenSerialStreamResponse>* SerialService::Stub::AsyncOpenSerialStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::rb::api::OpenSerialStreamRequest, ::rb::api::OpenSerialStreamResponse>::Create(channel_.get(), cq, rpcmethod_OpenSerialStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::rb::api::OpenSerialStreamRequest, ::rb::api::OpenSerialStreamResponse>* SerialService::Stub::PrepareAsyncOpenSerialStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::rb::api::OpenSerialStreamRequest, ::rb::api::OpenSerialStreamResponse>::Create(channel_.get(), cq, rpcmethod_OpenSerialStream_, context, false, nullptr);
}

SerialService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SerialService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SerialService::Service, ::rb::api::GetSerialDeviceListRequest, ::rb::api::GetSerialDeviceListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SerialService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rb::api::GetSerialDeviceListRequest* req,
             ::rb::api::GetSerialDeviceListResponse* resp) {
               return service->GetSerialDeviceList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SerialService_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< SerialService::Service, ::rb::api::OpenSerialStreamRequest, ::rb::api::OpenSerialStreamResponse>(
          [](SerialService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::rb::api::OpenSerialStreamResponse,
             ::rb::api::OpenSerialStreamRequest>* stream) {
               return service->OpenSerialStream(ctx, stream);
             }, this)));
}

SerialService::Service::~Service() {
}

::grpc::Status SerialService::Service::GetSerialDeviceList(::grpc::ServerContext* context, const ::rb::api::GetSerialDeviceListRequest* request, ::rb::api::GetSerialDeviceListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SerialService::Service::OpenSerialStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::rb::api::OpenSerialStreamResponse, ::rb::api::OpenSerialStreamRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rb
}  // namespace api

