set(__QT_DEPLOY_TARGET_RBY1DesktopQt_FILE C:/Users/ADMIN/source/repos/RBY1DesktopQt_Moc4_StatePattern/build-release/RBY1DesktopQt.exe)
set(__QT_DEPLOY_TARGET_RBY1DesktopQt_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_RBY1DesktopQt_RUNTIME_DLLS C:/Qt/6.11.1/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Network.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_RBY1DesktopQtTests_FILE C:/Users/ADMIN/source/repos/RBY1DesktopQt_Moc4_StatePattern/build-release/RBY1DesktopQtTests.exe)
set(__QT_DEPLOY_TARGET_RBY1DesktopQtTests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_RBY1DesktopQtTests_RUNTIME_DLLS C:/Qt/6.11.1/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Network.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Test.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Core.dll)
